// aboutTOEIC/daily-data.js — 토익 일일 문제 은행
// 150문항 = Day 1..15 × 10문제 (세트당 Part 5 ×8 + Part 6 ×1 + Part 7 ×1)
// shared/daily.js (window.NanamateDaily)가 DOMContentLoaded 시 #nm-daily-host에 자동 마운트.
// 이 파일은 daily.js보다 먼저 defer 로드되어야 함.
window.NANAMATE_DAILY = {
  kind: "quizset",
  subject: "TOEIC",
  accent: "#f59e0b",
  title: "토익 일일 문제",
  epoch: "2026-07-01",
  setSize: 10,
  questions: [
    // ══════════ Day 1 ══════════
    {part: 5, q: "The marketing team ___ a new campaign next month.",
     choices: ["will launch", "launched", "launch", "launching"], answer: 0,
     explain: "next month(다음 달)가 미래 시점을 나타내므로 미래시제 will launch가 정답. launch는 단수 주어 team과 수일치가 안 되고, launched는 과거시제, launching은 단독으로 본동사가 될 수 없어요."},
    {part: 5, q: "Please review the attached document ___ before signing it.",
     choices: ["careful", "more careful", "carefulness", "carefully"], answer: 3,
     explain: "동사 review를 수식하는 자리이므로 부사 carefully가 정답. careful/more careful은 형용사, carefulness는 명사라 동사를 수식할 수 없어요."},
    {part: 5, q: "___ the heavy rain, the outdoor event proceeded as planned.",
     choices: ["Despite", "Although", "Because", "Unless"], answer: 0,
     explain: "빈칸 뒤가 명사구(the heavy rain)이므로 전치사가 필요하고, '비에도 불구하고 진행됐다'는 양보 의미이므로 Despite가 정답. Although/Because/Unless는 접속사라 뒤에 절(주어+동사)이 와야 해요."},
    {part: 5, q: "The new software will ___ productivity by reducing manual data entry.",
     choices: ["entitle", "enlarge", "expend", "enhance"], answer: 3,
     explain: "enhance productivity '생산성을 향상시키다'가 자연스러운 연어. entitle은 '자격을 주다', enlarge는 '(크기를) 확대하다', expend는 '(돈·에너지를) 소비하다'로 의미가 맞지 않아요."},
    {part: 5, q: "Employees ___ have completed the training may access the lab.",
     choices: ["who", "whose", "whom", "which"], answer: 0,
     explain: "빈칸 뒤에 동사(have completed)가 바로 오므로 주격 관계대명사가 필요하고, 선행사가 사람(Employees)이므로 who가 정답. whose는 소유격, whom은 목적격, which는 사물용이에요."},
    {part: 5, q: "Neither the manager nor the assistants ___ available this afternoon.",
     choices: ["is", "was", "has been", "are"], answer: 3,
     explain: "neither A nor B는 동사와 가까운 주어 B(the assistants, 복수)에 수를 일치시키므로 are가 정답. is/was/has been은 모두 단수 동사예요."},
    {part: 5, q: "All applications must be submitted ___ October 15.",
     choices: ["by", "until", "since", "from"], answer: 0,
     explain: "제출처럼 한 번에 완료되는 동작의 마감 기한은 by(~까지는)를 써요. until은 상태·동작이 그 시점까지 '계속'될 때 쓰므로 부적절하고, since/from은 시작점을 나타내요."},
    {part: 6, passage: "To: All Staff\nSubject: Office Renovation\n\nThe third floor will be closed for renovation from July 10 to July 24. During this period, employees seated on that floor will ___ temporary desks on the fifth floor. We apologize for any inconvenience.",
     q: "빈칸에 들어갈 가장 알맞은 것은?",
     choices: ["be assigned", "assign", "have assigned", "assigning"], answer: 0,
     explain: "직원들은 임시 책상을 '배정하는' 주체가 아니라 '배정받는' 대상이므로 수동태 will be assigned가 정답. assign/have assigned는 능동이라 목적어 관계가 어긋나고, assigning은 will 뒤에 올 수 없어요."},
    {part: 7, passage: "NOTICE — Grandview Fitness Center will be closed on Monday, August 3, for annual equipment maintenance. Members may use our partner facility, Eastside Gym, free of charge on that day by showing their membership card. Normal hours will resume on Tuesday, August 4.",
     q: "What are members advised to bring to Eastside Gym?",
     choices: ["A day pass", "A maintenance form", "A payment receipt", "A membership card"], answer: 3,
     explain: "공지의 'by showing their membership card'(회원 카드를 제시하면 무료 이용 가능)에서 회원 카드가 필요함을 알 수 있어요. 나머지 선택지는 지문에 언급되지 않았어요."},
    {part: 5, q: "The results of the survey were ___ different from what we had expected.",
     choices: ["significantly", "signify", "significant", "significance"], answer: 0,
     explain: "형용사 different를 수식하는 자리이므로 부사 significantly가 정답. significant는 형용사, signify는 동사, significance는 명사라 형용사를 수식할 수 없어요."},

    // ══════════ Day 2 ══════════
    {part: 5, q: "Mr. Chen asked that the report ___ to him by noon.",
     choices: ["sends", "sent", "is sent", "be sent"], answer: 3,
     explain: "ask, request, demand 등 요청·요구 동사 뒤 that절에는 (should+)동사원형을 쓰는 가정법 현재가 와요. 보고서는 '보내지는' 대상이므로 수동 원형 be sent가 정답."},
    {part: 5, q: "The hotel is conveniently ___ near the airport and the convention center.",
     choices: ["located", "locating", "location", "locates"], answer: 0,
     explain: "be located '~에 위치해 있다'는 수동태 관용 표현이므로 과거분사 located가 정답. 건물이 스스로 위치시키는 게 아니라 위치된 것이므로 능동형 locating/locates는 오답이에요."},
    {part: 5, q: "___ you have any questions, please contact the HR department.",
     choices: ["Would", "Might", "Could", "Should"], answer: 3,
     explain: "If you should have any questions에서 if가 생략되고 should가 문두로 도치된 형태예요. '혹시 ~하면'의 조건 도치는 Should만 가능해요."},
    {part: 5, q: "Ticket holders are ___ to arrive at least 30 minutes before the performance.",
     choices: ["encouraged", "informed", "suggested", "insisted"], answer: 0,
     explain: "encourage는 'encourage+목적어+to부정사' 구조를 가지므로 수동태 be encouraged to가 가능해요. suggest/insist는 사람을 목적어로 취하지 않아 이런 수동태가 불가능하고, be informed는 뒤에 of/that이 와야 해요."},
    {part: 5, q: "The company's profits have risen ___ 15 percent since January.",
     choices: ["at", "among", "in", "by"], answer: 3,
     explain: "증가·감소의 '폭'을 나타낼 때는 by를 써요(15퍼센트만큼 올랐다). at은 지점, in은 분야·기간, among은 '~사이에'로 모두 어긋나요."},
    {part: 5, q: "___ completion of the internship, she was offered a full-time position.",
     choices: ["Upon", "While", "As soon as", "Now that"], answer: 0,
     explain: "빈칸 뒤가 명사구(completion of ~)이므로 전치사 Upon(~하자마자, ~와 동시에)이 정답. While/As soon as/Now that은 접속사라 뒤에 절이 와야 해요."},
    {part: 5, q: "Due to ___ demand, the workshop has been moved to a larger venue.",
     choices: ["popularity", "popularly", "popularize", "popular"], answer: 3,
     explain: "명사 demand를 수식하는 형용사 자리이므로 popular가 정답. due to popular demand '성원에 힘입어'는 자주 나오는 관용 표현이에요. popularity는 명사, popularly는 부사, popularize는 동사."},
    {part: 6, passage: "Effective March 1, all travel expenses must be submitted through the new online portal. Receipts ___ within 30 days of the travel date will not be reimbursed. Please direct questions to the finance team.",
     q: "빈칸에 들어갈 가장 알맞은 것은?",
     choices: ["not submitted", "do not submit", "not submitting", "are not submitted"], answer: 0,
     explain: "문장의 본동사는 will not be reimbursed이므로 빈칸은 Receipts를 뒤에서 수식하는 분사 자리예요. 영수증은 '제출되는' 대상이므로 과거분사 not submitted(= which are not submitted)가 정답."},
    {part: 7, passage: "From: laura.kim@brightech.com\nTo: service@officemax-supplies.com\nSubject: Order #4471\n\nI am writing about my recent order of 20 desk lamps. When the shipment arrived this morning, only 15 lamps were included, and two of them were damaged. Please send the missing lamps along with replacements for the damaged ones. I would also appreciate a confirmation once the new shipment is dispatched.",
     q: "How many additional lamps does Ms. Kim need in total?",
     choices: ["Two", "Five", "Twenty", "Seven"], answer: 3,
     explain: "주문 20개 중 15개만 도착했으므로 누락분 5개, 파손된 2개의 교환품 2개가 필요해요. 5 + 2 = 7개(Seven)가 정답. 간단한 계산을 요구하는 전형적인 Part 7 문제예요."},
    {part: 5, q: "The keynote speech was so ___ that many attendees stayed for the entire session.",
     choices: ["engaging", "engage", "engaged", "engagement"], answer: 0,
     explain: "연설이 사람들의 흥미를 '유발하는' 주체이므로 현재분사형 형용사 engaging(흥미진진한)이 정답. engaged는 '몰입한(사람의 감정 상태)'이라 사물 주어와 맞지 않아요."},

    // ══════════ Day 3 ══════════
    {part: 5, q: "Ms. Alvarez will be out of the office ___ the end of the week.",
     choices: ["by", "among", "within", "until"], answer: 3,
     explain: "'부재중'이라는 상태가 주말까지 계속되는 것이므로 지속의 until이 정답. by는 그 시점까지 동작이 '완료'될 때 쓰므로 상태 지속과는 맞지 않아요."},
    {part: 5, q: "Please ___ that all windows are locked before leaving the building.",
     choices: ["ensure", "assure", "insure", "reassure"], answer: 0,
     explain: "ensure that절 '~을 확실히 하다'가 정답. assure/reassure는 사람을 목적어로 취해 '(사람을) 안심시키다'이고, insure는 '보험에 들다'예요."},
    {part: 5, q: "TechCorp announced plans to merge ___ its largest competitor.",
     choices: ["to", "at", "for", "with"], answer: 3,
     explain: "merge with '~와 합병하다'가 올바른 전치사 결합이에요. merge to/for/at은 쓰지 않아요."},
    {part: 5, q: "___ of the board members attended the emergency meeting.",
     choices: ["Most", "Almost", "Mostly", "The most"], answer: 0,
     explain: "Most of the + 명사 '~의 대부분'이 정답. Almost는 부사라 of를 바로 취할 수 없고(Almost all of는 가능), Mostly도 부사, The most는 최상급이라 이 구조에 맞지 않아요."},
    {part: 5, q: "The warranty covers repairs but does not ___ to accidental damage.",
     choices: ["appeal", "attach", "arrive", "apply"], answer: 3,
     explain: "apply to '~에 적용되다'가 정답. appeal to는 '~에 호소하다/매력을 끌다', attach to는 '~에 붙(이)다', arrive는 '도착하다'로 보증 범위 문맥에 맞지 않아요."},
    {part: 5, q: "Had the shipment arrived on time, we ___ the deadline.",
     choices: ["would have met", "would meet", "met", "will meet"], answer: 0,
     explain: "Had the shipment arrived는 If the shipment had arrived의 도치(가정법 과거완료)예요. 주절은 would have p.p.가 짝이므로 would have met이 정답."},
    {part: 5, q: "All visitors must sign in at the front desk ___ arrival.",
     choices: ["until", "while", "when", "upon"], answer: 3,
     explain: "upon arrival '도착 시'는 전치사+명사의 관용 표현이에요. while/when은 접속사라 뒤에 절이 필요하고, until arrival은 '도착할 때까지 서명한다'가 되어 의미가 어긋나요."},
    {part: 6, passage: "Join Lakeside Books' annual summer sale! ___ July 8 through July 14, all paperback titles will be 30% off. Members receive an additional 10% discount. Visit us at 55 Harbor Street.",
     q: "빈칸에 들어갈 가장 알맞은 것은?",
     choices: ["From", "Between", "Since", "Along"], answer: 0,
     explain: "from A through B 'A부터 B까지'가 정답 짝이에요. Between은 and와 짝을 이루고(between A and B), Since는 완료시제와 어울리는 '~이후로', Along은 '~을 따라'예요."},
    {part: 7, passage: "Redwood Public Library — Workshop Series\nJuly 6: Résumé Writing (Room A)\nJuly 13: Interview Skills (Room A)\nJuly 20: Networking Basics (Room B)\nAll sessions begin at 6:30 P.M. Registration is required and can be completed online or at the information desk. Space is limited to 20 participants per session.",
     q: "What is indicated about the workshops?",
     choices: ["They are held in the morning.", "They are limited to library staff.", "They take place in the same room.", "They require advance registration."], answer: 3,
     explain: "'Registration is required'에서 사전 등록이 필요함을 알 수 있어요. 시작은 오후 6:30이라 morning이 아니고, 7/20은 Room B라 같은 방도 아니며, 참가 제한은 인원 20명이지 직원 한정이 아니에요."},
    {part: 5, q: "The revised handbook is much easier to understand ___ the previous edition.",
     choices: ["than", "from", "as", "over"], answer: 0,
     explain: "비교급 easier와 짝을 이루는 것은 than이에요. as는 원급 비교(as easy as), from은 different from처럼 쓰이고, over는 비교급과 직접 짝을 이루지 않아요."},

    // ══════════ Day 4 ══════════
    {part: 5, q: "___ its high price, the new smartphone has sold extremely well.",
     choices: ["Although", "Because of", "Even", "Despite"], answer: 3,
     explain: "빈칸 뒤가 명사구이고 '비싼데도 잘 팔렸다'는 양보 의미이므로 전치사 Despite가 정답. Although는 접속사(절 필요), Even은 단독으로 전치사가 아니고, Because of는 인과라 의미가 반대예요."},
    {part: 5, q: "Employees are reminded ___ their timesheets every Friday.",
     choices: ["to submit", "submit", "submitting", "submitted"], answer: 0,
     explain: "remind+목적어+to부정사 구조의 수동태 be reminded to do이므로 to submit이 정답."},
    {part: 5, q: "The finance director gave a ___ explanation of the quarterly results.",
     choices: ["brief", "briefly", "briefing", "brevity"], answer: 0,
     explain: "명사 explanation을 수식하는 형용사 자리이므로 brief(간결한)가 정답. briefly는 부사, briefing/brevity는 명사예요."},
    {part: 5, q: "Not only ___ the deadline, but she also came in under budget.",
     choices: ["she met", "met she", "she did meet", "did she meet"], answer: 3,
     explain: "부정어구 Not only가 문두에 오면 주어와 (조)동사가 도치돼요. 일반동사 met은 조동사 did를 빌려 did she meet 순서가 되는 게 정답."},
    {part: 5, q: "Please keep your receipt as ___ of purchase.",
     choices: ["proof", "proven", "prove", "approval"], answer: 0,
     explain: "proof of purchase '구매 증빙'이 관용 표현이에요. 전치사 as 뒤 명사 자리이기도 하고요. prove는 동사, proven은 분사, approval(승인)은 의미가 맞지 않아요."},
    {part: 5, q: "The office supply order should arrive ___ three business days.",
     choices: ["until", "from", "by", "within"], answer: 3,
     explain: "three business days는 '기간'이므로 within(~이내에)이 정답. by/until은 뒤에 시점이 와야 하고, from은 출발점이에요."},
    {part: 5, q: "Ms. Tanaka, ___ joined the firm in May, has already been promoted.",
     choices: ["which", "whom", "whose", "who"], answer: 3,
     explain: "선행사가 사람(Ms. Tanaka)이고 빈칸 뒤에 동사(joined)가 바로 오는 주격 자리이므로 who가 정답. which는 사물용, whom은 목적격, whose는 소유격이에요."},
    {part: 6, passage: "Dear Valued Customer,\n\nThank you for subscribing to CityWeekly. Your first issue will arrive within two weeks. ___, you can enjoy full access to our digital edition at cityweekly.com using the account information below.",
     q: "빈칸에 들어갈 가장 알맞은 것은?",
     choices: ["In the meantime", "On the other hand", "Therefore", "For instance"], answer: 0,
     explain: "'첫 호가 도착하기 전까지 그 사이에' 디지털판을 이용하라는 흐름이므로 In the meantime(그동안에)이 정답. Therefore(그러므로), On the other hand(반면에), For instance(예를 들어)는 앞뒤 논리가 맞지 않아요."},
    {part: 7, passage: "Mark Reyes (10:02 A.M.): The projector in Conference Room B isn't working. My client presentation starts at 10:30.\nDana Cho (10:04 A.M.): IT is fully booked this morning. Can you move to Room D? Its equipment was checked yesterday.\nMark Reyes (10:05 A.M.): That works. Could you update the room booking and let the front desk know so my clients are directed there?\nDana Cho (10:06 A.M.): Already on it.",
     q: "What will Dana Cho most likely do next?",
     choices: ["Repair the projector", "Cancel the presentation", "Call the clients directly", "Change a room reservation"], answer: 3,
     explain: "Mark가 'update the room booking'을 요청했고 Dana가 'Already on it(이미 하고 있어요)'이라고 답했으므로 회의실 예약 변경이 정답. 프로젝터 수리는 IT가 못 온다고 했고, 발표 취소나 고객 직접 연락은 언급되지 않았어요."},
    {part: 5, q: "The seminar has been postponed ___ further notice.",
     choices: ["by", "to", "in", "until"], answer: 3,
     explain: "until further notice '추후 공지가 있을 때까지'는 토익 단골 관용 표현이에요. 연기 상태가 공지 시점까지 지속되므로 until이 맞아요."},

    // ══════════ Day 5 ══════════
    {part: 5, q: "Each of the applicants ___ required to submit two references.",
     choices: ["are", "have been", "were", "is"], answer: 3,
     explain: "each는 항상 단수 취급이므로 단수 동사 is가 정답. of the applicants(복수)에 이끌려 are를 고르지 않도록 주의해야 해요."},
    {part: 5, q: "The airline offers a ___ shuttle service between the terminal and the hotel.",
     choices: ["complimentary", "complementary", "complimenting", "compliment"], answer: 0,
     explain: "complimentary는 '무료의'라는 뜻으로 complimentary shuttle/breakfast 등 토익 단골 표현이에요. 철자가 비슷한 complementary는 '보완하는'이라 의미가 달라요."},
    {part: 5, q: "___ the contract carefully before you sign it.",
     choices: ["Review", "Reviewing", "Reviewed", "Reviews"], answer: 0,
     explain: "주어 없이 시작하는 명령문이므로 동사원형 Review가 정답. Reviewing/Reviewed/Reviews는 명령문을 이끌 수 없어요."},
    {part: 5, q: "The manager was impressed ___ the intern's attention to detail.",
     choices: ["at", "on", "for", "with"], answer: 3,
     explain: "be impressed with/by '~에 감명받다'가 올바른 결합이에요. at/on/for는 impressed와 함께 쓰지 않아요."},
    {part: 5, q: "Sales figures for the second quarter were ___ higher than analysts had predicted.",
     choices: ["considerably", "considerable", "considering", "considerate"], answer: 0,
     explain: "비교급 형용사 higher를 수식하는 부사 자리이므로 considerably(상당히)가 정답. considerable은 형용사, considerate는 '배려심 있는'으로 뜻도 달라요."},
    {part: 5, q: "___ the new policy, employees may work remotely up to three days per week.",
     choices: ["On", "At", "Along", "Under"], answer: 3,
     explain: "under the policy '그 정책에 따라/하에서'가 올바른 표현이에요. 규정·법·계약 아래 놓인다는 의미로 전치사 under를 써요."},
    {part: 5, q: "Please make sure the conference room ___ before the clients arrive.",
     choices: ["is cleaned", "cleans", "cleaned", "cleaning"], answer: 0,
     explain: "회의실은 '청소되는' 대상이므로 수동태 is cleaned가 정답. cleans는 능동(회의실이 청소한다?)이라 어색하고, cleaned/cleaning만으로는 절의 동사가 될 수 없어요."},
    {part: 6, passage: "MEMO — Starting next Monday, the cafeteria will extend its hours ___ employees on the evening shift. Dinner service will be available from 6:00 to 8:30 P.M.",
     q: "빈칸에 들어갈 가장 알맞은 것은?",
     choices: ["accommodates", "accommodated", "accommodation", "to accommodate"], answer: 3,
     explain: "운영 시간을 연장하는 '목적'(저녁 근무 직원들을 수용하기 위해)을 나타내므로 to부정사 to accommodate가 정답. 본동사 will extend가 이미 있으므로 다른 동사형은 들어갈 수 없어요."},
    {part: 7, passage: "GREENFIELD FARMERS' MARKET — Every Saturday, 8 A.M.–1 P.M., Central Plaza. Fresh produce, baked goods, and handmade crafts from over 40 local vendors. Free parking is available in the City Hall garage. Interested in becoming a vendor? Applications are accepted year-round at greenfieldmarket.org.",
     q: "According to the advertisement, what can visitors do at the Web site?",
     choices: ["Reserve a parking space", "Purchase fresh produce", "Apply to become a vendor", "View a list of weekly events"], answer: 2,
     explain: "마지막 문장 'Applications are accepted year-round at greenfieldmarket.org'에서 웹사이트로 판매자 지원이 가능함을 알 수 있어요. 주차는 무료일 뿐 예약이 아니고, 농산물 구매는 현장에서 해요."},
    {part: 5, q: "The training session will begin ___ at 9:00 A.M.",
     choices: ["promptly", "prompt", "prompted", "prompting"], answer: 0,
     explain: "동사 begin을 수식하는 부사 자리이므로 promptly(정각에, 지체 없이)가 정답. begin promptly at + 시각은 안내문 단골 표현이에요."},

    // ══════════ Day 6 ══════════
    {part: 5, q: "___ arriving at the hotel, guests should present a valid photo ID.",
     choices: ["During", "Toward", "Until", "Upon"], answer: 3,
     explain: "upon -ing '~하자마자'가 정답. During은 뒤에 명사(기간)가 와야 자연스럽고(During arrival이 아닌 During the stay 등), Until/Toward는 의미가 맞지 않아요."},
    {part: 5, q: "The committee will ___ the proposals and announce its decision next week.",
     choices: ["evaluate", "estimate", "elevate", "emphasize"], answer: 0,
     explain: "제안서를 '평가하다'는 evaluate가 정답. estimate는 '(수치를) 추산하다', elevate는 '들어올리다', emphasize는 '강조하다'예요."},
    {part: 5, q: "Mr. Osei speaks three languages, ___ makes him a valuable member of the sales team.",
     choices: ["that", "who", "what", "which"], answer: 3,
     explain: "콤마 뒤에서 앞 절 전체(3개 국어를 한다는 사실)를 받는 계속적 용법의 관계대명사는 which예요. that은 콤마 뒤에 쓸 수 없고, what은 선행사를 포함해 여기 맞지 않아요."},
    {part: 5, q: "The device must be turned off ___ takeoff and landing.",
     choices: ["while", "when", "during", "since"], answer: 2,
     explain: "빈칸 뒤가 명사구(takeoff and landing)이므로 전치사 during(~동안)이 정답. while/when은 접속사라 절이 필요해요."},
    {part: 5, q: "Employees who exceed their sales targets are ___ for a year-end bonus.",
     choices: ["capable", "possible", "eligible", "probable"], answer: 2,
     explain: "be eligible for '~을 받을 자격이 있다'가 정답. capable은 of와 결합하고, possible/probable은 사람 주어와 이렇게 쓰지 않아요."},
    {part: 5, q: "By the time the auditors arrive, the finance team ___ all the records.",
     choices: ["organizes", "organized", "will have organized", "has organized"], answer: 2,
     explain: "By the time + 현재시제 절이 미래의 기준점을 나타내면, 주절은 그때까지 완료될 일을 나타내는 미래완료 will have p.p.를 써요."},
    {part: 5, q: "Applicants should send a résumé and cover letter ___ to the hiring manager.",
     choices: ["direction", "directs", "directive", "directly"], answer: 3,
     explain: "동사 send를 수식하여 '곧바로, 직접' 보내라는 의미의 부사 directly가 정답. direction(방향)·directive(지시)는 명사, directs는 동사예요."},
    {part: 6, passage: "Dear Mr. Walsh,\n\nWe received your application for the marketing coordinator position. ___ your qualifications are impressive, we have decided to move forward with another candidate whose experience more closely matches our needs. We encourage you to apply for future openings.",
     q: "빈칸에 들어갈 가장 알맞은 것은?",
     choices: ["Despite", "Because", "While", "Unless"], answer: 2,
     explain: "'자격은 인상적이지만 다른 후보로 결정했다'는 양보·대조이므로 접속사 While(~이긴 하지만)이 정답. Despite는 전치사라 절을 이끌 수 없고, Because는 인과라 뒤 내용과 모순돼요."},
    {part: 7, passage: "From: events@horizonhall.com\nTo: p.novak@midtowndesign.com\nSubject: Your reservation\n\nDear Ms. Novak,\nThis confirms your reservation of the Grand Room for December 12, 5–10 P.M., for approximately 80 guests. A deposit of $300 is due by November 20 to secure the booking. Catering must be arranged separately; a list of approved caterers is attached. Please note that decorations may not be attached to the walls.",
     q: "What is Ms. Novak asked to do by November 20?",
     choices: ["Confirm the guest count", "Submit a decoration plan", "Choose a caterer", "Pay a deposit"], answer: 3,
     explain: "'A deposit of $300 is due by November 20'에서 11월 20일까지 보증금을 내야 예약이 확정됨을 알 수 있어요. 케이터링은 별도 준비 사항일 뿐 기한이 없고, 장식은 벽 부착 금지 안내만 있어요."},
    {part: 5, q: "The museum is open every day ___ Mondays.",
     choices: ["without", "unless", "despite", "except"], answer: 3,
     explain: "except '~을 제외하고'가 정답(월요일만 휴관). without은 '~없이', unless는 접속사, despite는 '~에도 불구하고'라 의미가 맞지 않아요."},

    // ══════════ Day 7 ══════════
    {part: 5, q: "Ms. Ito reviewed the figures ___ before submitting the budget proposal.",
     choices: ["herself", "her", "hers", "she"], answer: 0,
     explain: "완전한 문장 뒤에서 주어를 강조하는 재귀대명사 herself(직접, 스스로)가 정답. her/hers/she는 이 자리에 문법적으로 들어갈 수 없어요."},
    {part: 5, q: "The road will remain closed while crews ___ repairs to the bridge.",
     choices: ["do", "give", "take", "make"], answer: 3,
     explain: "make repairs '수리하다'가 올바른 연어(collocation)예요. do/take/give는 repairs와 짝을 이루지 않아요."},
    {part: 5, q: "___ of the two designs was ultimately chosen by the client.",
     choices: ["None", "Both", "Neither", "Every"], answer: 2,
     explain: "'둘 중 어느 것도 아니다'는 Neither of the two가 정답이며 단수 동사 was와도 일치해요. None은 셋 이상에 쓰고, Both는 복수 동사가 필요하며, Every는 of를 바로 취할 수 없어요."},
    {part: 5, q: "The updated privacy policy takes ___ on September 1.",
     choices: ["affect", "effectively", "effective", "effect"], answer: 3,
     explain: "take effect '발효되다, 시행되다'가 관용 표현이에요. affect는 동사(영향을 주다)라 take의 목적어로 쓰지 않고, effective/effectively는 형용사/부사예요."},
    {part: 5, q: "Guests may leave their luggage at the front desk ___ their rooms are ready.",
     choices: ["by", "during", "until", "among"], answer: 2,
     explain: "빈칸 뒤가 절(their rooms are ready)이고 '방이 준비될 때까지' 맡겨두는 지속의 의미이므로 접속사 until이 정답. by/during/among은 전치사라 절을 이끌 수 없어요."},
    {part: 5, q: "Dr. Ramos is widely regarded ___ a leading expert in renewable energy.",
     choices: ["to", "for", "as", "like"], answer: 2,
     explain: "be regarded as '~로 여겨지다'가 올바른 결합이에요. regard A as B 구조의 수동태로, to/for/like는 쓰지 않아요."},
    {part: 5, q: "The instructions were written clearly so that even first-time users could follow ___.",
     choices: ["them", "they", "their", "themselves"], answer: 0,
     explain: "follow의 목적어는 the instructions(설명서)를 가리키는 대명사이므로 them이 정답. themselves를 쓰면 사용자가 '자기 자신을' 따라간다는 뜻이 되어 어색해요."},
    {part: 6, passage: "NOTICE — Beginning August 1, Parkside Tower will upgrade its elevator system. One elevator will remain in service at all times. The project is expected ___ by August 29. We appreciate your patience.",
     q: "빈칸에 들어갈 가장 알맞은 것은?",
     choices: ["to be completed", "completing", "to complete", "being completed"], answer: 0,
     explain: "be expected to do 구조인데, 프로젝트는 '완료되는' 대상이므로 수동형 to be completed가 정답. to complete는 능동이라 목적어가 필요하고, completing/being completed는 expected 뒤에 올 수 없어요."},
    {part: 7, passage: "HARBORTON (June 2) — Local bakery chain Miller & Grain announced yesterday that it will open two new locations this fall, one in Weston and another in Cedar Falls. Founded in 2015 as a single storefront, the company now operates twelve shops across the region. CEO Anita Miller credits the growth to the company's focus on locally sourced ingredients. \"Our suppliers are all within 50 miles of our kitchens,\" she said.",
     q: "What is suggested about Miller & Grain?",
     choices: ["It currently operates twelve shops.", "It was founded in Cedar Falls.", "It imports most of its ingredients.", "It plans to close its first store."], answer: 0,
     explain: "'the company now operates twelve shops'에서 현재 12개 매장을 운영 중임을 알 수 있어요. Cedar Falls는 신규 지점 예정지이고, 재료는 80km(50마일) 이내 지역 조달이라 수입이 아니며, 폐점 언급은 없어요."},
    {part: 5, q: "The new printer is capable ___ producing 40 pages per minute.",
     choices: ["to", "for", "of", "at"], answer: 2,
     explain: "be capable of -ing '~할 수 있다'가 올바른 결합이에요. capable to/for/at은 쓰지 않아요."},

    // ══════════ Day 8 ══════════
    {part: 5, q: "___ the merger is finalized, the combined company will employ over 5,000 people.",
     choices: ["Once", "Despite", "During", "Owing to"], answer: 0,
     explain: "빈칸 뒤가 절이고 '합병이 마무리되면'이라는 조건·시간의 의미이므로 접속사 Once(일단 ~하면)가 정답. Despite/During/Owing to는 전치사(구)라 절을 이끌 수 없어요."},
    {part: 5, q: "Attendance at the safety briefing is ___ for all warehouse staff.",
     choices: ["tentative", "mandatory", "redundant", "vacant"], answer: 1,
     explain: "안전 교육 참석은 '의무적'이라는 mandatory가 정답. tentative는 '잠정적인', redundant는 '불필요한', vacant는 '(자리가) 비어 있는'이에요."},
    {part: 5, q: "The report contains detailed ___ on regional sales trends.",
     choices: ["informations", "information", "informative", "informed"], answer: 1,
     explain: "information은 불가산 명사라 복수형 informations는 존재하지 않아요. 형용사 detailed의 수식을 받는 명사 information이 정답."},
    {part: 5, q: "Ms. Beck would rather review the contract herself ___ delegate the task.",
     choices: ["then", "than", "as", "but"], answer: 1,
     explain: "would rather A than B 'B하느니 차라리 A하겠다' 구문이므로 than이 정답. then(그때, 그다음)과 혼동하지 않도록 주의하세요."},
    {part: 5, q: "The airline ___ passengers of the gate change over the loudspeaker.",
     choices: ["announced", "said", "notified", "explained"], answer: 2,
     explain: "notify A of B 'A에게 B를 알리다'만이 사람을 직접 목적어로 취해요. announce/explain은 사물이 목적어(announce the change to passengers)이고, said도 사람을 목적어로 못 받아요."},
    {part: 5, q: "___ experienced staff members occasionally need refresher training.",
     choices: ["Even", "Ever", "Very", "Much"], answer: 0,
     explain: "Even '~조차, 심지어'가 명사구를 강조하는 정답이에요(숙련된 직원조차 재교육이 필요하다). Ever는 의문·부정문에서, Very/Much는 이런 강조 위치에 쓰지 않아요."},
    {part: 5, q: "The client requested that the invoice ___ into three installments.",
     choices: ["divide", "be divided", "divides", "dividing"], answer: 1,
     explain: "request that절에는 (should+)동사원형(가정법 현재)을 쓰고, 청구서는 '나뉘는' 대상이므로 수동 원형 be divided가 정답."},
    {part: 6, passage: "Dear Ms. Farrell,\n\nThank you for your purchase of the AeroDesk standing desk. To activate your three-year warranty, please register your product online within 30 days. ___, keep your original receipt, as it may be required for service claims.",
     q: "빈칸에 들어갈 가장 알맞은 것은?",
     choices: ["Otherwise", "Nevertheless", "Additionally", "Similarly"], answer: 2,
     explain: "'온라인 등록을 하라'에 이어 '영수증도 보관하라'는 정보를 덧붙이는 흐름이므로 Additionally(추가로)가 정답. Otherwise(그렇지 않으면), Nevertheless(그럼에도), Similarly(마찬가지로)는 논리가 맞지 않아요."},
    {part: 7, passage: "RIVERTOWN AUTO SERVICE — Invoice #20841\nCustomer: J. Park | Vehicle: 2022 Sedan\nOil change ............ $45\nTire rotation ......... $30\nBrake inspection ...... No charge (promotional)\nTotal: $75 — Paid by credit card\nNext recommended service: 5,000 km or six months, whichever comes first.",
     q: "What did Mr. Park receive at no cost?",
     choices: ["An oil change", "A tire rotation", "A brake inspection", "A credit card discount"], answer: 2,
     explain: "명세서에서 Brake inspection 항목이 'No charge (promotional)'로 표시되어 있으므로 브레이크 점검이 무료였어요. 오일 교환($45)과 타이어 로테이션($30)은 유료였어요."},
    {part: 5, q: "Ticket prices vary ___ on the day of the performance.",
     choices: ["depended", "depends", "dependent", "depending"], answer: 3,
     explain: "depending on '~에 따라'는 분사형 관용 표현이에요. 본동사 vary가 이미 있으므로 depends/depended는 올 수 없고, dependent는 be dependent on 형태로 써야 해요."},

    // ══════════ Day 9 ══════════
    {part: 5, q: "The CEO's speech was broadcast ___ to all regional offices.",
     choices: ["lively", "live", "alive", "living"], answer: 1,
     explain: "broadcast live '생중계로 방송되다'에서 live는 부사예요. lively(활기찬)는 형용사, alive는 서술 용법 형용사, living은 '살아 있는'으로 모두 방송 문맥과 맞지 않아요."},
    {part: 5, q: "Ms. Duarte has worked in the accounting department ___ 2019.",
     choices: ["for", "since", "during", "from"], answer: 1,
     explain: "현재완료(has worked) + 시작 시점(2019)이므로 since(~이후로 지금까지)가 정답. for는 기간(for five years), during은 특정 기간 명사와 써요."},
    {part: 5, q: "Please ___ from using mobile phones inside the auditorium.",
     choices: ["prevent", "prohibit", "refrain", "avoid"], answer: 2,
     explain: "refrain from -ing '~을 삼가다'가 정답. avoid는 전치사 없이 바로 목적어를 취하고(avoid using), prevent/prohibit은 금지 '대상'이 목적어로 필요해요(prevent A from -ing)."},
    {part: 5, q: "The proposal, ___ was submitted last week, is still under review.",
     choices: ["that", "which", "it", "what"], answer: 1,
     explain: "콤마 사이 삽입절(계속적 용법)을 이끄는 관계대명사는 which예요. that은 콤마 뒤에 쓸 수 없고, it은 관계대명사가 아니며, what은 선행사를 포함하는 관계사예요."},
    {part: 5, q: "___ quickly the team works, the project cannot be finished by Friday.",
     choices: ["Whatever", "However", "Whenever", "Whichever"], answer: 1,
     explain: "However + 부사/형용사 + 주어 + 동사 '아무리 ~해도'의 양보 구문이에요. Whatever/Whichever는 명사를, Whenever는 절을 다른 구조로 이끌어요."},
    {part: 5, q: "The two branches will be consolidated to reduce operating ___.",
     choices: ["worth", "prices", "costs", "fares"], answer: 2,
     explain: "operating costs '운영비'가 올바른 연어예요. prices는 판매 가격, fares는 교통 요금, worth는 가치라 지점 통합으로 줄이는 대상과 맞지 않아요."},
    {part: 5, q: "Ms. Osborn asked her assistant to make ten ___ of the agenda.",
     choices: ["copy", "copying", "copies", "copied"], answer: 2,
     explain: "수사 ten 뒤에는 복수 명사가 오므로 copies가 정답. make a copy/copies of '~의 사본을 만들다' 표현이에요."},
    {part: 6, passage: "To all tenants:\n\nWater service in the building will be temporarily shut off on Thursday, July 16, from 9 A.M. to 1 P.M. so that plumbers can replace an aging valve. We recommend storing water in advance for use ___ this period. Thank you for your cooperation.",
     q: "빈칸에 들어갈 가장 알맞은 것은?",
     choices: ["while", "during", "between", "along"], answer: 1,
     explain: "빈칸 뒤가 명사구(this period)이므로 전치사 during(~동안)이 정답. while은 접속사라 절이 필요하고, between은 A and B 짝이 필요해요."},
    {part: 7, passage: "POSITION: Customer Service Representative (Full-Time)\nHENLEY TELECOM — Downtown Office\nResponsibilities include answering customer inquiries by phone and e-mail, processing service orders, and updating account records. Requirements: two or more years of customer service experience, strong communication skills, and proficiency in spreadsheet software. Weekend shifts are required once per month. To apply, e-mail your résumé to careers@henleytelecom.com by July 31.",
     q: "What is a stated requirement for the position?",
     choices: ["A university degree", "Experience in customer service", "Fluency in a second language", "A driver's license"], answer: 1,
     explain: "Requirements 항목에 'two or more years of customer service experience'가 명시되어 있어요. 학위, 제2외국어, 운전면허는 지문에 없는 내용이에요."},
    {part: 5, q: "___ the two candidates, Ms. Lopez has the more relevant experience.",
     choices: ["Among", "From", "Of", "With"], answer: 2,
     explain: "'둘 중에서'는 Of the two + 비교급(the more ~) 구조를 써요. Among은 셋 이상 사이에서 쓰는 전치사예요."},

    // ══════════ Day 10 ══════════
    {part: 5, q: "All entries must be received no ___ than midnight on Friday.",
     choices: ["late", "later", "lately", "latest"], answer: 1,
     explain: "no later than '늦어도 ~까지'는 마감 표현의 관용구예요. than과 짝을 이루는 비교급 later가 정답. lately는 '최근에'라는 뜻의 부사예요."},
    {part: 5, q: "The hotel staff went out of their way to ___ the guests' special requests.",
     choices: ["accompany", "accommodate", "accumulate", "accelerate"], answer: 1,
     explain: "accommodate a request '요청을 수용하다'가 정답. accompany는 '동행하다', accumulate는 '축적하다', accelerate는 '가속하다'예요."},
    {part: 5, q: "The elevator is currently out of ___; please use the stairs.",
     choices: ["serving", "service", "served", "serve"], answer: 1,
     explain: "out of service '운행 중지, 고장'은 관용 표현이에요. 전치사 of 뒤 명사 자리이기도 하므로 service가 정답."},
    {part: 5, q: "___ signing the lease, tenants should inspect the apartment thoroughly.",
     choices: ["Until", "Toward", "Before", "Against"], answer: 2,
     explain: "'계약서에 서명하기 전에' 점검해야 한다는 의미이므로 Before(-ing) 가 정답. Until -ing는 어색하고, Toward/Against는 의미가 맞지 않아요."},
    {part: 5, q: "Ms. Grant was praised for handling the difficult negotiation so ___.",
     choices: ["skillful", "skill", "skillfully", "skilled"], answer: 2,
     explain: "동명사 handling(동사 성질)을 수식하는 부사 자리이므로 skillfully가 정답. so 뒤라고 형용사를 고르면 안 되고, 무엇을 수식하는지 봐야 해요."},
    {part: 5, q: "The parking garage is reserved ___ for employees of Norton Industries.",
     choices: ["exclusive", "exclusion", "excluded", "exclusively"], answer: 3,
     explain: "동사 is reserved를 수식하는 부사 exclusively(오로지, 독점적으로)가 정답. reserved exclusively for '~전용'은 자주 나오는 표현이에요."},
    {part: 5, q: "Sales representatives are expected to respond to customer inquiries ___ 24 hours.",
     choices: ["until", "within", "since", "by"], answer: 1,
     explain: "24 hours는 '기간'이므로 within(~이내에)이 정답. by/until은 시점과 함께 쓰고, since는 완료시제와 어울리는 시작점이에요."},
    {part: 6, passage: "From: HR Department\nSubject: Annual Performance Reviews\n\nPerformance reviews will take place during the first two weeks of October. Please complete your self-assessment form no later than September 25. Managers will then schedule individual meetings. ___ will receive an e-mail with available time slots next week.",
     q: "빈칸에 들어갈 가장 알맞은 것은?",
     choices: ["Employed", "Employees", "Employment", "Employer"], answer: 1,
     explain: "동사 will receive의 주어가 될 명사가 필요하고, 문맥상 이메일을 받는 것은 '직원들'이므로 복수 명사 Employees가 정답. Employer는 단수라 관사 없이 주어로 쓸 수 없고, Employment(고용)는 의미가 어긋나요."},
    {part: 7, passage: "Dear Subscriber,\n\nOur records show that your subscription to Tech Monthly will expire on August 31. Renew by August 1 to receive a 20% early-renewal discount. As always, subscribers enjoy unlimited access to our online archive, which contains every issue published since 1998. To renew, visit techmonthly.com/renew or call 555-0182.",
     q: "What benefit is offered for renewing by August 1?",
     choices: ["A free gift", "A reduced price", "An extra issue", "Access to an archive"], answer: 1,
     explain: "'Renew by August 1 to receive a 20% early-renewal discount'에서 조기 갱신 혜택은 20% 할인, 즉 가격 인하예요. 아카이브 이용은 모든 구독자가 원래 누리는 혜택이라 조기 갱신의 보상이 아니에요."},
    {part: 5, q: "Neither of the printers on the third floor ___ working properly.",
     choices: ["is", "are", "were", "have been"], answer: 0,
     explain: "neither는 단수 취급이므로 단수 동사 is가 정답. of the printers(복수)에 이끌려 are를 고르지 않도록 주의하세요."},

    // ══════════ Day 11 ══════════
    {part: 5, q: "The seminar attracted ___ 200 participants from across the country.",
     choices: ["approximate", "approximation", "approximately", "approximates"], answer: 2,
     explain: "수사 200을 수식하는 것은 부사 approximately(약, 대략)예요. approximately/nearly/about + 숫자는 토익 단골 패턴이에요."},
    {part: 5, q: "Mr. Silva will act as interim director ___ a permanent replacement is hired.",
     choices: ["by", "until", "within", "onto"], answer: 1,
     explain: "빈칸 뒤가 절이고 '후임자가 채용될 때까지' 직무대행이 지속되므로 접속사 until이 정답. by/within/onto는 전치사라 절을 이끌 수 없어요."},
    {part: 5, q: "Construction of the new wing is ___ ahead of schedule.",
     choices: ["preceding", "proceeding", "processing", "possessing"], answer: 1,
     explain: "proceed '진행되다'의 진행형 proceeding이 정답(공사가 일정보다 빨리 진행 중). precede는 '~보다 앞서다', process는 '처리하다', possess는 '소유하다'예요."},
    {part: 5, q: "___ who wish to attend the banquet must RSVP by Friday.",
     choices: ["They", "Them", "Those", "That"], answer: 2,
     explain: "Those who '~하는 사람들'이 정답. 관계사절 who의 수식을 받을 수 있는 대명사는 Those뿐이에요."},
    {part: 5, q: "The memo clearly states ___ the new dress code will take effect.",
     choices: ["what", "which", "who", "when"], answer: 3,
     explain: "빈칸 뒤가 완전한 절(the new dress code will take effect)이므로 명사절 접속사 중 완전한 절을 이끄는 when(언제 시행되는지)이 정답. what/which/who는 뒤에 불완전한 절이 와야 해요."},
    {part: 5, q: "Because of a scheduling ___, the meeting was moved to Thursday.",
     choices: ["contrast", "dispute", "conflict", "refusal"], answer: 2,
     explain: "scheduling conflict '일정 겹침'이 올바른 연어예요. contrast(대조), dispute(분쟁), refusal(거절)은 scheduling과 짝을 이루지 않아요."},
    {part: 5, q: "Employees may park in Lot B ___ they display a valid permit.",
     choices: ["in case of", "due to", "provided that", "instead of"], answer: 2,
     explain: "빈칸 뒤가 절이고 '허가증을 게시한다면'이라는 조건이므로 접속사 provided that(~라는 조건 하에)이 정답. 나머지는 모두 전치사(구)라 절을 이끌 수 없어요."},
    {part: 6, passage: "ATTENTION SHOPPERS — Rowan's Department Store will be introducing a new rewards program next month. Current cardholders will be enrolled ___ and will keep all previously earned points. Details will be mailed to your registered address.",
     q: "빈칸에 들어갈 가장 알맞은 것은?",
     choices: ["automatic", "automate", "automatically", "automation"], answer: 2,
     explain: "수동태 동사 will be enrolled를 수식하는 부사 automatically(자동으로)가 정답. automatic은 형용사, automate는 동사, automation은 명사예요."},
    {part: 7, passage: "MEMO\nTo: Warehouse Staff\nFrom: Operations Manager\nRe: Inventory Count\n\nThe annual inventory count is scheduled for Saturday, September 12. All staff who volunteer to work that day will be paid at 1.5 times their normal hourly rate and will receive a catered lunch. Sign-up sheets are posted in the break room until September 4. We need at least 15 volunteers to complete the count in one day.",
     q: "Why would staff members most likely sign up by September 4?",
     choices: ["To reserve a parking space", "To receive extra pay for working on September 12", "To order a special lunch menu", "To avoid the inventory count"], answer: 1,
     explain: "자원자는 통상 시급의 1.5배를 받는다고 했으므로, 9월 4일까지 신청하는 이유는 재고 조사일 근무로 추가 수당을 받기 위해서예요. 점심은 제공되는 것이지 주문하는 게 아니에요."},
    {part: 5, q: "The manual explains how to install the software ___.",
     choices: ["step by step", "step to step", "steps by steps", "by step of step"], answer: 0,
     explain: "step by step '단계별로, 차근차근'이 올바른 관용 표현이에요. 나머지는 존재하지 않는 형태예요."},

    // ══════════ Day 12 ══════════
    {part: 5, q: "Ms. Reyes is responsible ___ coordinating all international shipments.",
     choices: ["of", "for", "to", "with"], answer: 1,
     explain: "be responsible for '~을 담당하다, 책임지다'가 올바른 결합이에요. responsible of/to/with는 쓰지 않아요."},
    {part: 5, q: "The auditorium can ___ up to 500 people.",
     choices: ["sit", "seat", "seated", "sitting"], answer: 1,
     explain: "seat는 타동사로 '(장소가) ~명을 수용하다'라는 뜻이 있어요(The hall seats 500). sit은 자동사라 목적어를 취할 수 없고, can 뒤에는 동사원형이 와야 해요."},
    {part: 5, q: "Please note that prices are subject ___ change without notice.",
     choices: ["of", "to", "for", "on"], answer: 1,
     explain: "be subject to change '변경될 수 있다'는 약관·안내문의 단골 관용 표현이에요. 이때 to는 전치사예요."},
    {part: 5, q: "___ the invitations were sent early, few people attended the reception.",
     choices: ["Despite", "Because of", "Although", "Unless"], answer: 2,
     explain: "'초대장을 일찍 보냈는데도 적게 왔다'는 양보 관계이고 빈칸 뒤가 절이므로 접속사 Although가 정답. Despite/Because of는 전치사구라 절을 이끌 수 없어요."},
    {part: 5, q: "The intern quickly became ___ with the company's filing system.",
     choices: ["similar", "common", "familiar", "usual"], answer: 2,
     explain: "become familiar with '~에 익숙해지다'가 정답. similar는 '비슷한'(similar to), common은 '흔한', usual은 '평소의'로 의미와 결합이 맞지 않아요."},
    {part: 5, q: "The bakery's sales have nearly doubled ___ the past two years.",
     choices: ["since", "over", "until", "among"], answer: 1,
     explain: "over the past two years '지난 2년에 걸쳐'가 정답. since는 뒤에 시점(since 2024)이 와야 하고 기간 명사와는 쓰지 않아요."},
    {part: 5, q: "A copy of the itinerary will be provided to ___ attendee.",
     choices: ["all", "most", "few", "each"], answer: 3,
     explain: "빈칸 뒤가 단수 명사 attendee이므로 each(각각의)가 정답. all/most/few는 복수 명사와 함께 써요."},
    {part: 6, passage: "Dear Mr. Adeyemi,\n\nThank you for speaking at last week's leadership conference. Attendee feedback was overwhelmingly positive, and many participants said your session was the most ___ part of the event. We hope to welcome you back next year.",
     q: "빈칸에 들어갈 가장 알맞은 것은?",
     choices: ["valuable", "value", "valuably", "values"], answer: 0,
     explain: "the most ___ part에서 명사 part를 수식하는 형용사 자리이므로 valuable이 정답(가장 유익한 순서). value/values는 명사, valuably는 부사예요."},
    {part: 7, passage: "TRANSIT CARD FAQ\nQ: Where can I reload my card?\nA: At any station kiosk, at participating convenience stores, or through our mobile app.\nQ: What if my card is lost or stolen?\nA: Registered cards can be frozen online, and the remaining balance transferred to a new card for a $5 fee. Unregistered cards cannot be replaced.\nQ: Do cards expire?\nA: Cards remain valid for ten years from the date of last use.",
     q: "According to the FAQ, why should riders register their transit cards?",
     choices: ["To avoid reloading fees", "To extend the card's expiration date", "To protect their balance if the card is lost", "To receive mobile app discounts"], answer: 2,
     explain: "등록된 카드만 분실 시 정지 및 잔액 이전이 가능하고, 미등록 카드는 교체가 불가하다고 했어요. 즉 등록의 이점은 분실 시 잔액 보호예요. 충전 수수료나 유효기간 연장, 앱 할인은 언급되지 않았어요."},
    {part: 5, q: "The company picnic will be held outdoors, weather ___.",
     choices: ["permits", "permitting", "permitted", "permission"], answer: 1,
     explain: "weather permitting '날씨가 허락하면'은 독립분사구문의 관용 표현이에요. 그대로 외워두면 좋은 토익 단골 표현이에요."},

    // ══════════ Day 13 ══════════
    {part: 5, q: "Ms. Chow has proven ___ to be a dependable team leader.",
     choices: ["her", "she", "hers", "herself"], answer: 3,
     explain: "prove oneself (to be) '자신이 ~임을 입증하다'로, 주어와 목적어가 같은 사람이므로 재귀대명사 herself가 정답."},
    {part: 5, q: "The store offers a full refund ___ items returned within 30 days.",
     choices: ["under", "on", "among", "into"], answer: 1,
     explain: "a refund on '~에 대한 환불'이 올바른 결합이에요. under/among/into는 refund와 짝을 이루지 않아요."},
    {part: 5, q: "___ the training manual carefully will help new hires avoid common errors.",
     choices: ["Read", "Reading", "Reads", "Readable"], answer: 1,
     explain: "문장의 주어 자리이므로 동명사 Reading(읽는 것)이 정답. 동명사 주어는 단수 취급이라 will help와도 자연스러워요. Read/Reads는 동사, Readable은 형용사예요."},
    {part: 5, q: "The flight to Denver was delayed ___ two hours because of fog.",
     choices: ["in", "at", "by", "on"], answer: 2,
     explain: "delayed by two hours '2시간만큼 지연되다'처럼 지연·증감의 '폭'은 by로 나타내요. in/at/on은 시간의 폭과 맞지 않아요."},
    {part: 5, q: "All laboratory personnel must wear ___ clothing at all times.",
     choices: ["protected", "protective", "protecting", "protection"], answer: 1,
     explain: "protective clothing '보호복'이 올바른 연어예요. protective는 '보호하는 기능의'라는 형용사이고, protected는 '보호받는', protection은 명사예요."},
    {part: 5, q: "Mr. Nkosi asked ___ the quarterly report was ready for distribution.",
     choices: ["that", "what", "whether", "which"], answer: 2,
     explain: "'보고서가 준비됐는지 아닌지' 물었다는 간접의문이므로 whether(~인지)가 정답. ask that은 요청의 의미로 뒤에 동사원형이 와야 하고, what/which는 불완전한 절을 이끌어요."},
    {part: 5, q: "Applicants must remain ___ under pressure.",
     choices: ["calmly", "calm", "calmness", "calmer"], answer: 1,
     explain: "remain은 2형식 동사라 보어로 형용사를 취하므로 calm이 정답. 부사 calmly는 보어가 될 수 없고, calmer는 비교 대상이 없어 어색해요."},
    {part: 6, passage: "NOTICE TO PASSENGERS — Due to track maintenance, the 6:15 express train to Colton will not run from July 20 to July 24. Passengers are advised to take the 6:05 local train, ___ arrives in Colton at 7:10 A.M.",
     q: "빈칸에 들어갈 가장 알맞은 것은?",
     choices: ["which", "it", "that", "what"], answer: 0,
     explain: "콤마 뒤에서 the 6:05 local train을 보충 설명하는 계속적 용법이므로 which가 정답. that은 콤마 뒤에 쓸 수 없고, it을 쓰면 접속사 없이 두 절이 연결되어 비문이 돼요."},
    {part: 7, passage: "★★★★☆ — Verified purchase\nI bought the Trailmax 40L backpack for a two-week trip through the mountains. The waterproof material worked perfectly during three days of rain, and the padded straps stayed comfortable even with a full load. My only complaint is that the side pockets are too small to hold a standard water bottle. Overall, I would recommend it to anyone who hikes regularly.",
     q: "What does the reviewer criticize about the backpack?",
     choices: ["Its weight", "Its price", "The size of its pockets", "The quality of its straps"], answer: 2,
     explain: "'My only complaint is that the side pockets are too small'에서 유일한 불만은 옆 주머니 크기임을 알 수 있어요. 방수 소재와 어깨끈은 오히려 칭찬했고, 무게나 가격은 언급되지 않았어요."},
    {part: 5, q: "___ he had little experience, Mr. Ford was hired for his enthusiasm.",
     choices: ["Despite", "Although", "Because of", "In spite of"], answer: 1,
     explain: "빈칸 뒤가 절(he had little experience)이므로 접속사 Although가 정답. Despite/In spite of는 전치사구라 명사가 와야 하고, Because of는 전치사구인 데다 인과 의미라 두 번 어긋나요."},

    // ══════════ Day 14 ══════════
    {part: 5, q: "Please have your boarding pass ___ for inspection.",
     choices: ["readily", "readiness", "ready", "readying"], answer: 2,
     explain: "have + 목적어 + 형용사 '~을 …한 상태로 두다' 구조이므로 형용사 ready가 정답(탑승권을 준비된 상태로 들고 계세요). readily는 부사, readiness는 명사예요."},
    {part: 5, q: "The seminar will cover a wide ___ of topics, from budgeting to marketing.",
     choices: ["area", "range", "distance", "length"], answer: 1,
     explain: "a wide range of '광범위한, 다양한'이 올바른 연어예요. area/distance/length는 wide와 함께 이 의미로 쓰지 않아요."},
    {part: 5, q: "Ms. Vega checked the figures twice to make sure they were ___.",
     choices: ["accurately", "accurate", "accuracy", "accusing"], answer: 1,
     explain: "be동사 were의 보어 자리이므로 형용사 accurate(정확한)가 정답. accurately는 부사, accuracy는 명사, accusing은 '비난하는'으로 뜻이 달라요."},
    {part: 5, q: "The library's renovation, ___ nearly two years, was finally completed in March.",
     choices: ["lasting which", "which lasted", "it lasted", "that lasted"], answer: 1,
     explain: "콤마 사이에서 renovation을 보충 설명하는 계속적 용법이므로 which lasted(거의 2년이 걸린)가 정답. that은 콤마 뒤 불가, it lasted는 접속사가 없어 비문이에요."},
    {part: 5, q: "Passengers should ___ their seat belts whenever the sign is illuminated.",
     choices: ["tighten", "strengthen", "fasten", "lengthen"], answer: 2,
     explain: "fasten one's seat belt '안전벨트를 매다'가 올바른 연어예요. tighten은 '조이다', strengthen은 '강화하다', lengthen은 '길게 하다'예요."},
    {part: 5, q: "___ ordering in bulk, customers can save up to 25 percent.",
     choices: ["With", "At", "By", "To"], answer: 2,
     explain: "By -ing '~함으로써'가 수단·방법을 나타내는 정답이에요(대량 주문함으로써 최대 25% 절약)."},
    {part: 5, q: "The results will be announced ___ the judges have finished their deliberations.",
     choices: ["as long", "as soon as", "so that", "in order to"], answer: 1,
     explain: "'심사위원들이 심의를 마치는 대로' 발표된다는 시간의 의미이므로 as soon as가 정답. as long은 as가 빠진 미완성 형태이고, so that은 목적, in order to는 뒤에 동사원형이 와야 해요."},
    {part: 6, passage: "From: fitness@corepoint.com\nSubject: Class Schedule Update\n\nDear Members,\nBeginning in September, our morning yoga class will move from 7:00 to 6:30 A.M. to better serve members who commute early. All other classes remain ___. The full schedule is available on our Web site.",
     q: "빈칸에 들어갈 가장 알맞은 것은?",
     choices: ["unchangeable", "changing", "unchanged", "changed"], answer: 2,
     explain: "remain unchanged '변동 없이 그대로다'가 정답(요가만 시간 변경, 나머지는 그대로). unchangeable은 '변경 불가능한'이라는 속성이고, changed를 쓰면 '변경된 채로 유지된다'는 반대 의미가 돼요."},
    {part: 7, passage: "From: t.harmon@vexatravel.com\nTo: r.okafor@bluepine.com\nSubject: Your trip to Chicago\n\nDear Mr. Okafor,\nHere is your itinerary: Flight VX214 departs Austin at 8:05 A.M. on Tuesday, arriving in Chicago at 10:40 A.M. Your return flight, VX219, departs Chicago at 6:30 P.M. on Thursday. I was unable to book your preferred hotel, as it is hosting a convention that week; instead, I reserved a room at the Lakeview Inn, two blocks away. Let me know if you would like me to look at other options.",
     q: "Why was Mr. Okafor's preferred hotel unavailable?",
     choices: ["It was closed for renovations.", "It had raised its prices.", "It is hosting a convention that week.", "It was too far from the airport."], answer: 2,
     explain: "'I was unable to book your preferred hotel, as it is hosting a convention that week'에서 선호 호텔이 그 주에 컨벤션을 개최해 예약이 불가했음을 알 수 있어요."},
    {part: 5, q: "Employees must obtain approval ___ making any purchases over $500.",
     choices: ["before", "until", "despite", "among"], answer: 0,
     explain: "'구매하기 전에' 승인을 받아야 한다는 의미이므로 before(-ing)가 정답. until -ing는 어색하고, despite/among은 의미가 맞지 않아요."},

    // ══════════ Day 15 ══════════
    {part: 5, q: "The candidate's experience in logistics makes her well ___ for the role.",
     choices: ["suiting", "suitably", "suit", "suited"], answer: 3,
     explain: "be well suited for '~에 적임이다'가 관용 표현이에요. makes her (well) suited의 목적격 보어 자리로 과거분사 suited가 정답."},
    {part: 5, q: "Due to a system upgrade, online banking will be ___ unavailable this Sunday.",
     choices: ["temporary", "temporarily", "temporariness", "temporal"], answer: 1,
     explain: "형용사 unavailable을 수식하는 부사 temporarily(일시적으로)가 정답. temporary는 형용사, temporal은 '시간의'라는 뜻으로 달라요."},
    {part: 5, q: "___ questions regarding payroll should be directed to Ms. Hale.",
     choices: ["Every", "Each", "Any", "Much"], answer: 2,
     explain: "복수 명사 questions 앞에 올 수 있는 것은 Any뿐이에요. Every/Each는 단수 명사와, Much는 불가산 명사와 써요."},
    {part: 5, q: "The board meeting has been rescheduled ___ next Wednesday.",
     choices: ["on", "in", "for", "at"], answer: 2,
     explain: "reschedule A for + 새 일정 '~로 일정을 변경하다'가 올바른 결합이에요. be scheduled for와 같은 패턴으로 기억해 두세요."},
    {part: 5, q: "Mr. Tran's ___ to detail makes him an excellent proofreader.",
     choices: ["intention", "attention", "attraction", "tension"], answer: 1,
     explain: "attention to detail '꼼꼼함, 세부에 대한 주의'가 올바른 연어예요. intention은 '의도'(intention to do), attraction은 '매력', tension은 '긴장'이에요."},
    {part: 5, q: "___ the office closes early on Fridays, staff often schedule client calls in the morning.",
     choices: ["Despite", "During", "Since", "Except"], answer: 2,
     explain: "빈칸 뒤가 절이고 '일찍 닫기 때문에'라는 이유이므로 접속사 Since(~때문에)가 정답. Despite/During/Except는 전치사라 절을 이끌 수 없어요."},
    {part: 5, q: "The workshop is designed for managers ___ teams work remotely.",
     choices: ["whose", "who", "whom", "which"], answer: 0,
     explain: "managers와 teams의 소유 관계(매니저들의 팀)를 나타내는 소유격 관계대명사 whose가 정답. 빈칸 뒤에 명사(teams)가 바로 오는 것이 소유격의 힌트예요."},
    {part: 6, passage: "Dear Ms. Petrov,\n\nEnclosed is the signed contract for the Harborview project. Please return one copy ___ your signature by Friday, June 5. Construction can begin once both copies are on file.",
     q: "빈칸에 들어갈 가장 알맞은 것은?",
     choices: ["on", "with", "at", "of"], answer: 1,
     explain: "'서명이 된 상태로(서명과 함께)' 한 부를 반송해 달라는 의미이므로 with your signature가 정답. on/at/of는 이 문맥의 결합으로 맞지 않아요."},
    {part: 7, passage: "COMMUNITY CENTER — FALL COURSE REGISTRATION\nRegistration opens Monday, August 24, at 9 A.M. Courses fill quickly; last fall, three of our five courses reached capacity within two days. Residents receive a 15% discount on all course fees. Proof of residency, such as a utility bill, must be shown at registration.\n\nCourses: Beginner Spanish (Tue), Watercolor Painting (Wed), Digital Photography (Thu), Yoga (Fri), Creative Writing (Sat)",
     q: "What must residents show to receive a discount?",
     choices: ["A registration form", "A course schedule", "Proof of residency", "A photo ID"], answer: 2,
     explain: "'Proof of residency, such as a utility bill, must be shown at registration'에서 할인을 받으려면 거주 증빙(예: 공과금 고지서)을 제시해야 함을 알 수 있어요."},
    {part: 5, q: "Thanks to the new tracking system, customers can now monitor their orders in ___ time.",
     choices: ["right", "real", "true", "exact"], answer: 1,
     explain: "in real time '실시간으로'가 올바른 관용 표현이에요. right/true/exact는 time과 이 의미로 결합하지 않아요."}
  ]
};
