// aboutEnglish/daily-data.js — 오늘의 영어 데이터 뱅크 (shared/daily.js보다 먼저 defer 로드)
// LessonItem: {badge, front, mean, ex, exMean, hint}
window.NANAMATE_DAILY = {
  kind: 'lesson', subject: 'ENGLISH', accent: '#3b82f6',
  title: '오늘의 영어', epoch: '2026-07-01', perDay: 5, quizPerDay: 3,
  items: [
    // ---- 표현 (이디엄) — ch.5 회화 / ch.9 미디어 ----
    {badge:'표현', front:'get the hang of', mean:'~의 요령을 익히다', ex:"You'll get the hang of it soon.", exMean:'금방 요령이 붙을 거예요.', hint:'[겟 더 행 오브]'},
    {badge:'표현', front:'break the ice', mean:'어색한 분위기를 깨다', ex:'He told a joke to break the ice.', exMean:'그는 분위기를 풀려고 농담을 했다.', hint:'[브레이크 디 아이스]'},
    {badge:'표현', front:'a piece of cake', mean:'식은 죽 먹기, 아주 쉬운 일', ex:'The test was a piece of cake.', exMean:'시험은 식은 죽 먹기였어.', hint:'[어 피스 어브 케이크]'},
    {badge:'표현', front:'under the weather', mean:'몸이 좀 안 좋은', ex:"I'm feeling a bit under the weather today.", exMean:'오늘 몸이 좀 안 좋아요.', hint:'[언더 더 웨더]'},
    {badge:'표현', front:'call it a day', mean:'오늘은 여기까지 하다', ex:"Let's call it a day and go home.", exMean:'오늘은 이만하고 집에 가자.', hint:'[콜 잇 어 데이]'},
    {badge:'표현', front:'in the same boat', mean:'같은 (어려운) 처지인', ex:"We're all in the same boat.", exMean:'우린 모두 같은 처지야.', hint:'[인 더 세임 보웃]'},
    {badge:'표현', front:'sleep on it', mean:'하룻밤 자며 생각해 보다', ex:'Let me sleep on it and decide tomorrow.', exMean:'하룻밤 생각해 보고 내일 결정할게.', hint:'[슬립 온 잇]'},
    {badge:'표현', front:'ring a bell', mean:'어렴풋이 기억나다, 들어 본 것 같다', ex:'That name rings a bell.', exMean:'그 이름 어디서 들어 본 것 같아.', hint:'[링 어 벨]'},
    {badge:'표현', front:'on the fence', mean:'결정을 못 내리고 망설이는', ex:"I'm still on the fence about the offer.", exMean:'그 제안에 대해 아직 망설이고 있어.', hint:'[온 더 펜스]'},
    {badge:'표현', front:'cost an arm and a leg', mean:'값이 엄청나게 비싸다', ex:'That car costs an arm and a leg.', exMean:'저 차는 값이 어마어마해.', hint:'[코스트 언 암 앤 어 레그]'},
    // ---- 구동사 — ch.4 어휘 / ch.5 회화 ----
    {badge:'구동사', front:'figure out', mean:'알아내다, 이해하다', ex:"I can't figure out how this works.", exMean:'이게 어떻게 작동하는지 모르겠어.', hint:'[피겨 아웃]'},
    {badge:'구동사', front:'put off', mean:'미루다, 연기하다', ex:"Don't put off until tomorrow what you can do today.", exMean:'오늘 할 수 있는 일을 내일로 미루지 마라.', hint:'[풋 오프]'},
    {badge:'구동사', front:'run into', mean:'우연히 마주치다', ex:'I ran into an old friend at the station.', exMean:'역에서 옛 친구와 우연히 마주쳤어.', hint:'[런 인투]'},
    {badge:'구동사', front:'come up with', mean:'(아이디어·해결책을) 생각해 내다', ex:'She came up with a brilliant idea.', exMean:'그녀가 기막힌 아이디어를 냈다.', hint:'[컴 업 위드]'},
    {badge:'구동사', front:'look forward to', mean:'~을 고대하다 (to 뒤엔 명사·동명사)', ex:'I look forward to seeing you.', exMean:'만나 뵙기를 고대합니다.', hint:'[룩 포워드 투]'},
    {badge:'구동사', front:'turn down', mean:'거절하다; (소리를) 줄이다', ex:'She turned down the job offer.', exMean:'그녀는 그 일자리 제안을 거절했다.', hint:'[턴 다운]'},
    {badge:'구동사', front:'bring up', mean:'(화제를) 꺼내다; (아이를) 키우다', ex:'He brought up an interesting point.', exMean:'그가 흥미로운 논점을 꺼냈다.', hint:'[브링 업]'},
    {badge:'구동사', front:'sort out', mean:'해결하다, 정리하다', ex:'We need to sort out this problem first.', exMean:'이 문제부터 해결해야 해.', hint:'[소트 아웃]'},
    {badge:'구동사', front:'catch up on', mean:'밀린 것을 따라잡다', ex:'I need to catch up on sleep this weekend.', exMean:'이번 주말엔 밀린 잠을 자야 해.', hint:'[캐치 업 온]'},
    {badge:'구동사', front:'put up with', mean:'참다, 견디다', ex:"I can't put up with the noise anymore.", exMean:'그 소음을 더는 못 참겠어.', hint:'[풋 업 위드]'},
    // ---- 연어 (collocation) — ch.4 어휘 확장 ----
    {badge:'연어', front:'make a decision', mean:'결정을 내리다 (do ✗)', ex:'We have to make a decision by Friday.', exMean:'금요일까지 결정을 내려야 해.', hint:'[메이크 어 디시전]'},
    {badge:'연어', front:'heavy rain', mean:'폭우 (strong rain ✗)', ex:'The game was canceled due to heavy rain.', exMean:'폭우로 경기가 취소됐다.', hint:'[헤비 레인]'},
    {badge:'연어', front:'strong coffee', mean:'진한 커피 (반대는 weak coffee)', ex:'I need a cup of strong coffee this morning.', exMean:'오늘 아침엔 진한 커피 한 잔이 필요해.', hint:'[스트롱 커피]'},
    {badge:'연어', front:'take a break', mean:'잠깐 쉬다', ex:"Let's take a break for ten minutes.", exMean:'10분만 쉬자.', hint:'[테이크 어 브레이크]'},
    {badge:'연어', front:'pay attention', mean:'주의를 기울이다', ex:'Please pay attention to the details.', exMean:'세부 사항에 주의를 기울여 주세요.', hint:'[페이 어텐션]'},
    {badge:'연어', front:'do research', mean:'연구·조사를 하다 (make ✗)', ex:"She's doing research on climate change.", exMean:'그녀는 기후 변화를 연구하고 있다.', hint:'[두 리서치]'},
    {badge:'연어', front:'keep a promise', mean:'약속을 지키다', ex:'He always keeps his promises.', exMean:'그는 언제나 약속을 지킨다.', hint:'[킵 어 프라미스]'},
    {badge:'연어', front:'meet a deadline', mean:'마감을 지키다 (놓치면 miss)', ex:'We worked all night to meet the deadline.', exMean:'마감을 맞추려고 밤새 일했다.', hint:'[미트 어 데드라인]'},
    {badge:'연어', front:'save time', mean:'시간을 절약하다', ex:'Taking the subway saves time.', exMean:'지하철을 타면 시간이 절약된다.', hint:'[세이브 타임]'},
    {badge:'연어', front:'heavy traffic', mean:'극심한 교통 정체', ex:'I was late because of heavy traffic.', exMean:'길이 많이 막혀서 늦었어.', hint:'[헤비 트래픽]'},
    // ---- 패턴 (회화·스몰토크) — ch.5 회화 패턴 ----
    {badge:'패턴', front:'I was wondering if ...', mean:'혹시 ~해 주실 수 있을까요 (가장 공손한 부탁)', ex:'I was wondering if you could help me.', exMean:'혹시 저 좀 도와주실 수 있을까요?', hint:'[아이 워즈 원더링 이프]'},
    {badge:'패턴', front:'Would you mind -ing?', mean:'~해 주시겠어요? (수락은 Not at all)', ex:'Would you mind opening the window?', exMean:'창문 좀 열어 주시겠어요?', hint:'[우쥬 마인드]'},
    {badge:'패턴', front:"It's been a while.", mean:'오랜만이야.', ex:"It's been a while! How have you been?", exMean:'오랜만이다! 그동안 어떻게 지냈어?', hint:'[이츠 빈 어 와일]'},
    {badge:'패턴', front:"I'm afraid ...", mean:'(유감이지만) ~인 것 같아요 — 부드러운 거절', ex:"I'm afraid I can't make it tomorrow.", exMean:'죄송하지만 내일은 못 갈 것 같아요.', hint:'[아임 어프레이드]'},
    {badge:'패턴', front:'It depends.', mean:'상황에 따라 달라요.', ex:'Do you eat out often? — It depends on the week.', exMean:'자주 외식하냐고? 주마다 달라.', hint:'[잇 디펜즈]'},
    {badge:'패턴', front:"How's it going?", mean:'잘 지내? (가벼운 인사)', ex:"Hey, how's it going? — Pretty good.", exMean:'안녕, 잘 지내? — 잘 지내.', hint:'[하우즈 잇 고잉]'},
    {badge:'패턴', front:'Let me get back to you.', mean:'확인하고 다시 알려 드릴게요.', ex:'Let me get back to you on that by tomorrow.', exMean:'그 건은 내일까지 확인해서 알려 드릴게요.', hint:'[렛 미 겟 백 투 유]'},
    {badge:'패턴', front:'If I were you, ...', mean:'내가 너라면 ~할 거야 (가정법 조언)', ex:"If I were you, I'd take the offer.", exMean:'내가 너라면 그 제안을 받아들일 거야.', hint:'[이프 아이 워 유]'},
    {badge:'패턴', front:'long story short', mean:'요약하자면, 한마디로', ex:'Long story short, we missed the flight.', exMean:'한마디로, 우리는 비행기를 놓쳤어.', hint:'[롱 스토리 쇼트]'},
    {badge:'패턴', front:'That works for me.', mean:'저는 그거 좋아요 (일정·제안 수락)', ex:'Friday at 3? That works for me.', exMean:'금요일 3시? 저는 좋아요.', hint:'[댓 웍스 포 미]'},
    {badge:'패턴', front:'No worries.', mean:'괜찮아요, 신경 쓰지 마세요.', ex:"Sorry I'm late! — No worries.", exMean:'늦어서 미안! — 괜찮아.', hint:'[노 워리즈]'},
    {badge:'패턴', front:'My bad.', mean:'내 잘못이야 (캐주얼한 사과)', ex:'Oh, my bad. I sent you the wrong file.', exMean:'아 미안, 파일을 잘못 보냈네.', hint:'[마이 배드]'},
    // ---- 비즈니스 — ch.8 이메일·회의 ----
    {badge:'비즈니스', front:'touch base', mean:'짧게 연락해 상황을 공유하다', ex:"Let's touch base next week about the project.", exMean:'다음 주에 프로젝트 관련해서 짧게 얘기해요.', hint:'[터치 베이스]'},
    {badge:'비즈니스', front:'circle back', mean:'나중에 다시 논의하다', ex:"Let's circle back to this after lunch.", exMean:'이 건은 점심 후에 다시 얘기합시다.', hint:'[서클 백]'},
    {badge:'비즈니스', front:'follow up', mean:'후속 조치를 하다, 다시 확인하다', ex:"I'll follow up with an email.", exMean:'이메일로 후속 안내 드리겠습니다.', hint:'[팔로우 업]'},
    {badge:'비즈니스', front:'keep ~ in the loop', mean:'~에게 진행 상황을 계속 공유하다', ex:'Please keep me in the loop on this issue.', exMean:'이 건 진행 상황을 계속 공유해 주세요.', hint:'[킵 미 인 더 루프]'},
    {badge:'비즈니스', front:'on the same page', mean:'같은 이해·인식을 갖고 있는', ex:"Let's make sure we're all on the same page.", exMean:'우리 모두 같은 이해인지 확인합시다.', hint:'[온 더 세임 페이지]'},
    {badge:'비즈니스', front:'reach out', mean:'연락하다, 연락을 취하다', ex:'Feel free to reach out if you have questions.', exMean:'질문 있으시면 언제든 연락 주세요.', hint:'[리치 아웃]'},
    {badge:'비즈니스', front:'Please find attached ...', mean:'~을 첨부하오니 확인 바랍니다 (이메일 정형)', ex:'Please find attached the final report.', exMean:'최종 보고서를 첨부하오니 확인 바랍니다.', hint:'[플리즈 파인드 어태치트]'},
    {badge:'비즈니스', front:'heads-up', mean:'미리 알림, 귀띔', ex:'Just a heads-up: the meeting moved to 4 p.m.', exMean:'미리 알려 드려요, 회의가 4시로 옮겨졌어요.', hint:'[헤즈업]'},
    {badge:'비즈니스', front:'take this offline', mean:'(회의에서) 이 논의는 따로 하다', ex:"Let's take this offline and move on.", exMean:'이 건은 따로 얘기하고 다음으로 넘어가죠.', hint:'[테이크 디스 오프라인]'},
    {badge:'비즈니스', front:'action item', mean:'실행 항목, 회의에서 정한 할 일', ex:"Let's review the action items from last meeting.", exMean:'지난 회의의 실행 항목을 점검합시다.', hint:'[액션 아이템]'},
    // ---- 발음 (최소대립쌍) — ch.2 발음과 청해 ----
    {badge:'발음', front:'ship vs. sheep', mean:'배 vs. 양 — /ɪ/ 짧고 느슨하게 vs /iː/ 길고 긴장되게', ex:'The ship carried a hundred sheep.', exMean:'그 배는 양 백 마리를 실었다.', hint:'[쉽 / 쉬-프]'},
    {badge:'발음', front:'full vs. fool', mean:'가득 찬 vs. 바보 — /ʊ/ vs /uː/', ex:"Don't be a fool — the tank is already full.", exMean:'바보같이 굴지 마, 탱크는 이미 가득 찼어.', hint:'[풀 / 푸-울]'},
    {badge:'발음', front:'right vs. light', mean:'옳은 vs. 빛 — R은 혀끝을 안 대고, L은 윗잇몸에 댄다', ex:'Turn right at the traffic light.', exMean:'신호등에서 우회전하세요.', hint:'[롸이트 / 을라이트]'},
    {badge:'발음', front:'rice vs. lice', mean:'쌀 vs. 이(벌레) — R/L 구분이 뜻을 가른다', ex:'We eat rice, not lice.', exMean:'우리는 쌀을 먹지, 이를 먹지 않는다.', hint:'[롸이스 / 을라이스]'},
    {badge:'발음', front:'fan vs. van', mean:'선풍기 vs. 승합차 — F 무성음 vs V 유성음(성대 울림)', ex:'A fan fell off the van.', exMean:'선풍기가 승합차에서 떨어졌다.', hint:'[f팬 / v밴]'},
    {badge:'발음', front:'walk vs. work', mean:'걷다 vs. 일하다 — /ɔː/ vs /ɜːr/', ex:'I walk to work every day.', exMean:'나는 매일 걸어서 출근한다.', hint:'[워-크 / 워r크]'},
    {badge:'발음', front:'coat vs. caught', mean:'코트 vs. 잡았다(catch 과거) — /oʊ/ vs /ɔː/', ex:'He caught the coat before it fell.', exMean:'그는 코트가 떨어지기 전에 잡았다.', hint:'[코웃 / 코-트]'},
    {badge:'발음', front:'bad vs. bed', mean:'나쁜 vs. 침대 — /æ/ 입을 크게 vs /e/', ex:'A bad bed ruins your sleep.', exMean:'나쁜 침대는 잠을 망친다.', hint:'[배애드 / 베드]'},
    {badge:'발음', front:'think vs. sink', mean:'생각하다 vs. 가라앉다 — th는 혀끝을 이 사이에', ex:'I think the boat will sink.', exMean:'배가 가라앉을 것 같아.', hint:'[θ씽크 / 씽크]'},
    {badge:'발음', front:'year vs. ear', mean:'해(年) vs. 귀 — year는 /j/ 반모음으로 시작', ex:'My ears get cold this time of year.', exMean:'이맘때면 귀가 시려요.', hint:'[이여r / 이어r]'},
    // ---- 뉘앙스 단어 — ch.3 문법 / ch.4 어휘 ----
    {badge:'뉘앙스', front:'borrow vs. lend', mean:'빌려 오다 vs. 빌려주다', ex:"Can I borrow your pen? — Sure, I'll lend it to you.", exMean:'펜 좀 빌려도 돼? — 응, 빌려줄게.', hint:'[바로우 / 렌드]'},
    {badge:'뉘앙스', front:'fun vs. funny', mean:'즐거운 vs. 웃긴 (헷갈리면 뜻이 달라짐)', ex:'The trip was fun, and the guide was funny.', exMean:'여행은 즐거웠고 가이드는 웃겼다.', hint:'[펀 / 퍼니]'},
    {badge:'뉘앙스', front:'hear vs. listen', mean:'(저절로) 들리다 vs. 귀 기울여 듣다', ex:'I heard music, so I stopped to listen.', exMean:'음악 소리가 들려서 멈춰 서서 귀 기울였다.', hint:'[히어 / 리슨]'},
    {badge:'뉘앙스', front:'see vs. watch', mean:'(눈에) 보이다 vs. 지켜보다', ex:'I saw a bird and watched it build a nest.', exMean:'새를 봤고, 둥지 짓는 걸 지켜봤다.', hint:'[시- / 워치]'},
    {badge:'뉘앙스', front:'say vs. tell', mean:'say+말한 내용 vs. tell+사람', ex:'He said sorry and told me the reason.', exMean:'그는 사과했고 내게 이유를 말해 줬다.', hint:'[세이 / 텔]'},
    {badge:'뉘앙스', front:'hope vs. wish', mean:'실현 가능한 바람 vs. 현실과 반대인 소망', ex:"I hope it's sunny tomorrow. I wish I were taller.", exMean:'내일 맑았으면 좋겠어. 내 키가 더 컸다면 좋을 텐데.', hint:'[호웁 / 위시]'},
    {badge:'뉘앙스', front:'remember vs. remind', mean:'스스로 기억하다 vs. 남에게 상기시키다', ex:'Remind me to call him — I never remember.', exMean:'그에게 전화하라고 알려 줘, 난 늘 까먹거든.', hint:'[리멤버 / 리마인드]'},
    {badge:'뉘앙스', front:'expect', mean:'예상하다 (설레는 기대는 look forward to)', ex:'I expect the meeting to run long.', exMean:'회의가 길어질 거라고 예상해.', hint:'[익스펙트]'},
    {badge:'뉘앙스', front:'actually', mean:'사실은 (정정할 때 씀 — "지금"이란 뜻 아님)', ex:'Actually, the store opens at 11, not 10.', exMean:'사실 그 가게는 10시가 아니라 11시에 열어.', hint:'[액추얼리]'},
    {badge:'뉘앙스', front:'almost', mean:'거의 (부사 — almost all로 쓰고 almost people ✗)', ex:'Almost all the tickets are sold out.', exMean:'표가 거의 다 팔렸다.', hint:'[올모우스트]'},

    // ---- 확장: 표현 II (2026-07-29 영어 강화) ----
    {badge:'표현', front:'hit the books', mean:'공부에 매진하다', ex:"Finals are next week — time to hit the books.", exMean:'기말고사가 다음 주야 — 공부 빡세게 할 때지.', hint:'[힛 더 북스]'},
    {badge:'표현', front:'spill the beans', mean:'비밀을 누설하다', ex:"Come on, spill the beans — what did she say?", exMean:'자, 불어 봐 — 그녀가 뭐라고 했어?', hint:'[스필 더 빈즈]'},
    {badge:'표현', front:'once in a blue moon', mean:'아주 드물게', ex:'We only go there once in a blue moon.', exMean:'우린 거긴 정말 가끔만 가.', hint:'[원스 인 어 블루 문]'},
    {badge:'표현', front:'bite the bullet', mean:'이를 악물고 하다, 감수하다', ex:"I hate dentist visits, but I'll bite the bullet.", exMean:'치과는 싫지만 감수하고 갈게.', hint:'[바이트 더 불릿]'},
    {badge:'표현', front:'the ball is in your court', mean:'이제 네 차례·네 결정이다', ex:"I've made my offer — the ball is in your court.", exMean:'제안은 했어 — 이제 네 결정이야.', hint:'[더 볼 이즈 인 유어 코트]'},
    {badge:'표현', front:'cut to the chase', mean:'본론으로 들어가다', ex:"Let's cut to the chase: do we have a deal?", exMean:'본론만 말하자. 계약할 거야?', hint:'[컷 투 더 체이스]'},
    {badge:'표현', front:'go the extra mile', mean:'기대 이상으로 애쓰다', ex:'She always goes the extra mile for her clients.', exMean:'그녀는 고객을 위해 늘 한 걸음 더 한다.', hint:'[고 디 엑스트라 마일]'},
    {badge:'표현', front:'keep me posted', mean:'진행 상황 계속 알려 줘', ex:'Keep me posted on the results.', exMean:'결과 나오면 계속 알려 줘.', hint:'[킵 미 포스티드]'},
    // ---- 확장: 구동사 II ----
    {badge:'구동사', front:'work out', mean:'운동하다; (일이) 잘 풀리다', ex:"Things worked out better than we expected.", exMean:'일이 예상보다 잘 풀렸어.', hint:'[워크 아웃]'},
    {badge:'구동사', front:'give up', mean:'포기하다', ex:"Don't give up — you're almost there.", exMean:'포기하지 마, 거의 다 왔어.', hint:'[기브 업]'},
    {badge:'구동사', front:'find out', mean:'알아내다, 알게 되다', ex:'I just found out about the schedule change.', exMean:'일정 변경 소식을 방금 알았어.', hint:'[파인드 아웃]'},
    {badge:'구동사', front:'set up', mean:'설치하다, 준비하다, 설립하다', ex:"Let's set up a call for Thursday.", exMean:'목요일에 통화 잡자.', hint:'[셋 업]'},
    {badge:'구동사', front:'break down', mean:'고장 나다; 분석하다; 감정을 주체 못 하다', ex:'Can you break down the costs for me?', exMean:'비용 좀 항목별로 나눠 줄래?', hint:'[브레이크 다운]'},
    {badge:'구동사', front:'carry on', mean:'계속하다', ex:'Sorry for the interruption — please carry on.', exMean:'방해해서 미안, 계속하세요.', hint:'[캐리 온]'},
    {badge:'구동사', front:'look into', mean:'조사하다, 살펴보다', ex:"I'll look into the issue and get back to you.", exMean:'그 문제 살펴보고 다시 연락드릴게요.', hint:'[룩 인투]'},
    {badge:'구동사', front:'run out of', mean:'~이 다 떨어지다', ex:"We've run out of printer paper.", exMean:'프린터 용지가 다 떨어졌어.', hint:'[런 아웃 어브]'},
    // ---- 확장: 연어 II ----
    {badge:'연어', front:'take responsibility', mean:'책임을 지다', ex:'Someone has to take responsibility for the mistake.', exMean:'누군가 그 실수에 책임을 져야 한다.', hint:'[테이크 리스폰서빌리티]'},
    {badge:'연어', front:'raise a question', mean:'문제를 제기하다', ex:'Her comment raised an important question.', exMean:'그녀의 발언이 중요한 문제를 제기했다.', hint:'[레이즈 어 퀘스천]'},
    {badge:'연어', front:'draw a conclusion', mean:'결론을 내리다', ex:"It's too early to draw a conclusion.", exMean:'결론을 내리기엔 너무 이르다.', hint:'[드로 어 컨클루전]'},
    {badge:'연어', front:'gain experience', mean:'경험을 쌓다', ex:'Internships help you gain experience.', exMean:'인턴십은 경험을 쌓는 데 도움이 된다.', hint:'[게인 익스피리언스]'},
    {badge:'연어', front:'catch a cold', mean:'감기에 걸리다 (get a cold도 가능)', ex:'I caught a cold on the flight.', exMean:'비행기에서 감기에 걸렸어.', hint:'[캐치 어 콜드]'},
    {badge:'연어', front:'have a conversation', mean:'대화를 나누다', ex:"I'd like to have a conversation about your goals.", exMean:'목표에 대해 이야기 나누고 싶어요.', hint:'[해브 어 컨버세이션]'},
    {badge:'연어', front:'set a goal', mean:'목표를 세우다', ex:'Set a goal that is specific and measurable.', exMean:'구체적이고 측정 가능한 목표를 세워라.', hint:'[셋 어 골]'},
    {badge:'연어', front:'miss the point', mean:'요점을 놓치다', ex:"I think you're missing the point.", exMean:'요점을 놓치고 있는 것 같아.', hint:'[미스 더 포인트]'},
    // ---- 확장: 패턴 II ----
    {badge:'패턴', front:'As far as I know, ...', mean:'제가 알기로는...', ex:'As far as I know, the meeting is still on.', exMean:'제 알기로는 회의는 그대로예요.', hint:'[애즈 파 애즈 아이 노우]'},
    {badge:'패턴', front:'To be honest, ...', mean:'솔직히 말하면...', ex:'To be honest, I preferred the first option.', exMean:'솔직히 첫 번째 옵션이 더 좋았어.', hint:'[투 비 어니스트]'},
    {badge:'패턴', front:"What I'm trying to say is ...", mean:'제가 말하려는 건...', ex:"What I'm trying to say is we need more time.", exMean:'제 말은, 시간이 더 필요하다는 거예요.', hint:'[웻 암 트라이잉 투 세이]'},
    {badge:'패턴', front:'It turns out that ...', mean:'알고 보니...', ex:'It turns out that the rumor was false.', exMean:'알고 보니 소문은 거짓이었다.', hint:'[잇 턴즈 아웃 댓]'},
    {badge:'패턴', front:"I'll keep that in mind.", mean:'명심할게요 / 기억해 둘게요.', ex:"Thanks for the tip — I'll keep that in mind.", exMean:'팁 고마워, 기억해 둘게.', hint:'[아일 킵 댓 인 마인드]'},
    {badge:'패턴', front:'Feel free to ...', mean:'편하게 ~하세요', ex:'Feel free to ask questions anytime.', exMean:'언제든 편하게 질문하세요.', hint:'[필 프리 투]'},
    {badge:'패턴', front:'At the end of the day, ...', mean:'결국 / 따지고 보면...', ex:'At the end of the day, health comes first.', exMean:'결국 건강이 우선이야.', hint:'[앳 디 엔드 어브 더 데이]'},
    {badge:'패턴', front:"I couldn't agree more.", mean:'완전 동감이야.', ex:"I couldn't agree more — that's exactly the issue.", exMean:'완전 동감, 그게 바로 문제야.', hint:'[아이 쿠든트 어그리 모어]'},
    // ---- 확장: 비즈니스 II ----
    {badge:'비즈니스', front:'move the needle', mean:'의미 있는 변화를 만들다', ex:'We need ideas that actually move the needle.', exMean:'실제로 임팩트 있는 아이디어가 필요해요.', hint:'[무브 더 니들]'},
    {badge:'비즈니스', front:'low-hanging fruit', mean:'쉽게 달성할 수 있는 성과', ex:"Let's start with the low-hanging fruit.", exMean:'쉬운 성과부터 잡자.', hint:'[로 행잉 프루트]'},
    {badge:'비즈니스', front:'bandwidth', mean:'(비유) 여유 시간·처리 여력', ex:"I don't have the bandwidth for another project.", exMean:'다른 프로젝트를 맡을 여유가 없어요.', hint:'[밴드위스]'},
    {badge:'비즈니스', front:'synergy', mean:'시너지, 협업 효과 (남용 주의)', ex:'The merger created real synergy in R&D.', exMean:'합병이 R&D에서 실질 시너지를 냈다.', hint:'[시너지]'},
    {badge:'비즈니스', front:'ASAP', mean:'가능한 한 빨리 (As Soon As Possible)', ex:'Please send the file ASAP.', exMean:'파일을 가능한 한 빨리 보내 주세요.', hint:'[에이십 / 에이에스에이피]'},
    {badge:'비즈니스', front:'EOD', mean:'업무 종료 시점 (End Of Day)', ex:'I need your feedback by EOD.', exMean:'오늘 업무 종료 전까지 피드백이 필요해요.', hint:'[이오디]'},
    {badge:'비즈니스', front:'cc / bcc', mean:'참조 / 숨은 참조', ex:'Please cc me on that email.', exMean:'그 메일에 저 참조 넣어 주세요.', hint:'[씨씨 / 비씨씨]'},
    {badge:'비즈니스', front:'touchpoint', mean:'고객·이해관계자와의 접점', ex:'Every touchpoint should feel consistent.', exMean:'모든 접점이 일관되게 느껴져야 한다.', hint:'[터치포인트]'},
    // ---- 확장: 발음 II ----
    {badge:'발음', front:'leave vs. live', mean:'떠나다 vs. 살다 — /iː/ vs /ɪ/', ex:'I leave home to live abroad.', exMean:'나는 해외에서 살려고 집을 떠난다.', hint:'[리-브 / 리브]'},
    {badge:'발음', front:'pool vs. pull', mean:'수영장 vs. 당기다 — /uː/ vs /ʊ/', ex:'Pull the door and jump in the pool.', exMean:'문을 당기고 수영장에 뛰어들어.', hint:'[푸-울 / 풀]'},
    {badge:'발음', front:'three vs. tree', mean:'셋 vs. 나무 — th vs t', ex:'Three trees grew by the road.', exMean:'길가에 나무 세 그루가 자랐다.', hint:'[쓰리 / 트리]'},
    {badge:'발음', front:'very vs. berry', mean:'매우 vs. 베리 — v vs b', ex:'This berry is very sweet.', exMean:'이 베리는 아주 달다.', hint:'[베리 / 베리(b)]'},
    {badge:'발음', front:'clothes vs. close', mean:'옷 vs. 닫다 — /ðz/ vs /z/', ex:'Close the closet with your clothes inside.', exMean:'옷을 넣은 채 옷장을 닫아라.', hint:'[클로우즈(ð) / 클로우즈]'},
    {badge:'발음', front:'desert vs. dessert', mean:'사막 vs. 디저트 — 강세 위치', ex:'In the desert, dessert feels special.', exMean:'사막에서는 디저트가 특별하게 느껴진다.', hint:'[데절트 / 디절트]'},
    // ---- 확장: 뉘앙스 II ----
    {badge:'뉘앙스', front:'job vs. work', mean:'job=직업·자리 / work=일(불가산)', ex:"I love my job, but there's too much work this week.", exMean:'직업은 좋은데 이번 주 일이 너무 많아.', hint:'[잡 / 워크]'},
    {badge:'뉘앙스', front:'travel vs. trip', mean:'travel=여행하다(동·개념) / trip=구체적인 여행', ex:'I travel often; my last trip was to Busan.', exMean:'자주 여행하는데, 최근 여행은 부산이었어.', hint:'[트래블 / 트립]'},
    {badge:'뉘앙스', front:'house vs. home', mean:'house=건물 / home=정이 든 공간', ex:'This house became our home.', exMean:'이 집이 우리의 보금자리가 됐다.', hint:'[하우스 / 홈]'},
    {badge:'뉘앙스', front:'win vs. beat', mean:'win+경기·상 / beat+상대', ex:'We won the match; we beat the champions.', exMean:'우리는 경기에서 이겼고, 챔피언을 꺾었다.', hint:'[윈 / 비트]'},
    {badge:'뉘앙스', front:'raise vs. rise', mean:'raise=타동(올리다) / rise=자동(오르다)', ex:'They raised prices; costs rose too.', exMean:'그들이 가격을 올렸고, 비용도 올랐다.', hint:'[레이즈 / 라이즈]'},
    {badge:'뉘앙스', front:'affect vs. effect', mean:'affect=영향을 주다(동) / effect=결과·효과(명)', ex:'The policy will affect us; the effect is unclear.', exMean:'정책이 우리에게 영향을 줄 테고, 효과는 불분명하다.', hint:'[어펙트 / 이펙트]'},
    {badge:'뉘앙스', front:'advice vs. advise', mean:'advice=명사 / advise=동사', ex:'She advised me; her advice was gold.', exMean:'그녀가 조언해 줬고, 그 조언은 금이었다.', hint:'[어드바이스 / 어드바이즈]'},
    {badge:'뉘앙스', front:'lie vs. lay', mean:'lie=눕다(lay/lain) / lay=놓다(laid)', ex:'Lay the book down and lie on the sofa.', exMean:'책을 놓고 소파에 누워.', hint:'[라이 / 레이]'},

  ],
  quiz: [
    {q:'"~의 요령을 익히다"에 해당하는 표현은?', choices:['get over','get the hang of','get rid of','get along with'], answer:1, explain:'get over는 극복하다, get rid of는 없애다, get along with는 ~와 잘 지내다.'},
    {q:'"어색한 분위기를 깨다"를 뜻하는 표현은?', choices:['break even','break the news','break the ice','break a leg'], answer:2, explain:'break a leg는 "행운을 빌어", break the news는 소식을 처음 알리다, break even은 본전치기하다.'},
    {q:'"몸이 좀 안 좋아요"를 뜻하는 표현은?', choices:['under the weather','over the moon','out of the blue','on cloud nine'], answer:0, explain:'over the moon과 on cloud nine은 "매우 기쁜", out of the blue는 "난데없이".'},
    {q:'"오늘은 여기까지 하자" — Let\'s ___ it a day.', choices:['make','take','put','call'], answer:3, explain:'call it a day가 고정 표현. "오늘 하루는 다 됐다고 부르다"라는 이미지.'},
    {q:'"그 이름 들어 본 것 같은데" — That name ___ a bell.', choices:['hits','rings','calls','knocks'], answer:1, explain:'ring a bell = 머릿속에서 종이 울리듯 어렴풋이 기억나다.'},
    {q:'"미루다"를 뜻하는 구동사는?', choices:['put on','put out','put off','put up'], answer:2, explain:'put on은 입다, put out은 (불을) 끄다, put up은 세우다·게시하다.'},
    {q:'"역에서 옛 친구와 우연히 마주쳤어" — I ___ an old friend at the station.', choices:['ran into','ran out of','ran over','ran away from'], answer:0, explain:'run into = 우연히 마주치다. run over는 차로 치다, run out of는 다 떨어지다.'},
    {q:'look forward to 뒤에 올 수 있는 형태는?', choices:['see you','to see you','seeing you','saw you'], answer:2, explain:'여기서 to는 전치사이므로 뒤에 명사나 동명사(-ing)가 온다.'},
    {q:'"(화제를) 꺼내다"를 뜻하는 구동사는?', choices:['bring back','bring up','bring down','bring about'], answer:1, explain:'bring back은 되돌려주다, bring down은 무너뜨리다, bring about은 야기하다.'},
    {q:'"참다, 견디다"를 뜻하는 구동사는?', choices:['put up with','come up with','get away with','catch up with'], answer:0, explain:'come up with는 생각해 내다, get away with는 처벌을 모면하다, catch up with는 따라잡다.'},
    {q:'"결정을 내리다"의 올바른 연어는?', choices:['do a decision','make a decision','have a decision','get a decision'], answer:1, explain:'decision은 make와 어울린다. do a decision은 한국어 화자가 자주 틀리는 조합.'},
    {q:'"폭우"의 올바른 연어는?', choices:['strong rain','big rain','heavy rain','fast rain'], answer:2, explain:'비·눈·교통량은 heavy로 표현한다 — heavy rain, heavy snow, heavy traffic.'},
    {q:'"진한 커피"의 올바른 연어는?', choices:['strong coffee','heavy coffee','thick coffee','powerful coffee'], answer:0, explain:'맛·농도의 진함은 strong. 반대는 weak coffee.'},
    {q:'"마감을 지키다"의 올바른 연어는?', choices:['catch a deadline','keep a deadline','hold a deadline','meet a deadline'], answer:3, explain:'deadline은 meet과 어울린다. 마감을 놓치면 miss a deadline.'},
    {q:'research와 어울리는 동사는?', choices:['make','do','take','give'], answer:1, explain:'do research가 표준 연어. make research는 틀린 조합.'},
    {q:'가장 공손한 부탁 표현은?', choices:['Help me with this.','I want you to help me.','I was wondering if you could help me.','You should help me.'], answer:2, explain:'I was wondering if...는 과거진행형으로 거리를 두어 가장 공손한 부탁이 된다.'},
    {q:'"Would you mind opening the window?"에 "네, 열어 드릴게요"로 답하려면?', choices:['Not at all.','Yes, I would.','Yes, I mind.','No, you may not.'], answer:0, explain:'mind는 "꺼리다"이므로 수락은 부정형(Not at all / Of course not)으로 답한다.'},
    {q:'"오랜만이야!"의 자연스러운 표현은?', choices:['It was a while!',"It's been a while!",'It is long time ago!','Long time no time!'], answer:1, explain:"It's been a while! 또는 Long time no see! 둘 다 자주 쓴다."},
    {q:'정중하게 "못 갈 것 같아요"라고 말하려면?', choices:['I refuse to go.',"I'm afraid I can't make it.","I don't come.",'Going is impossible for me.'], answer:1, explain:'I\'m afraid...는 유감을 담아 부드럽게 거절하는 장치. make it은 "참석하다, 시간 맞춰 가다".'},
    {q:'"요약하자면"에 해당하는 구어 표현은?', choices:['short story long','story in short','long story short','shortly speaking'], answer:2, explain:'long story short = "긴 이야기를 짧게 하자면". (To make a) long story short의 줄임.'},
    {q:'일정 제안에 "저는 좋아요"라고 답하는 자연스러운 표현은?', choices:['I am agree.','It makes for me.',"That's work to me.",'That works for me.'], answer:3, explain:'"I am agree"는 흔한 오류 — agree는 동사라 I agree. 일정 합의엔 That works for me.'},
    {q:'"짧게 연락해 상황을 공유하다"라는 비즈니스 표현은?', choices:['touch base','touch down','touch up','touch off'], answer:0, explain:'touch down은 착륙하다, touch up은 손보다, touch off는 촉발하다.'},
    {q:'"진행 상황을 계속 공유해 주세요" — Keep me in the ___.', choices:['circle','ring','chain','loop'], answer:3, explain:'in the loop = 정보가 도는 고리 안에 있는. 반대는 out of the loop.'},
    {q:'이메일에서 "보고서를 첨부하오니 확인 바랍니다"의 정형 표현은?', choices:['Please find attached the report.','Please look the attach.','I attach you the report.','Here is attach.'], answer:0, explain:'Please find attached ~ 또는 Attached is ~ 가 표준. attach는 사람을 목적어로 쓰지 않는다.'},
    {q:'"미리 알려 드려요"에 해당하는 표현은?', choices:['Just a hand-up','Just a heads-up','Just a head-down','Just an eyes-on'], answer:1, explain:'heads-up = 고개를 들게 하는 사전 경고·알림. Thanks for the heads-up처럼 쓴다.'},
    {q:'회의에서 "이 논의는 따로 합시다"는?', choices:["Let's log out.","Let's turn this off.","Let's take this offline.","Let's go offline together."], answer:2, explain:'take ~ offline은 회의 흐름을 위해 세부 논의를 별도 자리로 미루는 정형 표현.'},
    {q:'ship과 sheep의 발음을 구분 짓는 것은?', choices:['끝소리 p의 유무','강세 위치','sh 소리의 세기','모음의 길이와 긴장도 (/ɪ/ vs /iː/)'], answer:3, explain:'ship은 짧고 느슨한 /ɪ/, sheep은 길고 긴장된 /iː/.'},
    {q:'rice(쌀)가 lice(이)로 들리는 원인은?', choices:['R을 L처럼 발음','S를 Z처럼 발음','모음을 길게 발음','강세를 뒤에 둠'], answer:0, explain:'R은 혀끝이 어디에도 닿지 않고, L은 혀끝을 윗잇몸에 댄다.'},
    {q:'fan과 van의 차이를 만드는 것은?', choices:['모음의 길이','강세 위치','f는 무성음, v는 유성음(성대 울림)','끝 자음 n의 유무'], answer:2, explain:'둘 다 윗니를 아랫입술에 대지만 v는 성대를 울린다.'},
    {q:'think의 th를 발음하는 요령은?', choices:['혀를 목 쪽으로 말기','혀끝을 윗니와 아랫니 사이에 살짝 대기','입술을 동그랗게 오므리기','혀끝을 윗잇몸에 붙이기'], answer:1, explain:'th /θ/는 혀끝을 이 사이에 살짝 내밀고 바람을 내보낸다. 잇몸에 붙이면 s/t처럼 들린다.'},
    {q:'"펜 좀 빌려도 돼?"의 올바른 문장은?', choices:['Can you borrow me a pen?','Can I lend your pen?','Can I borrow your pen?','Do you lend me borrowing?'], answer:2, explain:'borrow는 빌려 오다, lend는 빌려주다. Can you lend me a pen?도 가능.'},
    {q:'"여행 정말 즐거웠어"의 올바른 표현은?', choices:['The trip was really funny.','The trip was really fun.','The trip was very laugh.','The trip was comic.'], answer:1, explain:'fun은 즐거운, funny는 웃긴. 여행이 우스꽝스러웠다는 뜻이 아니라면 fun.'},
    {q:'"그가 회의가 취소됐다고 나에게 말했다" — He ___ me that the meeting was canceled.', choices:['said','spoke','told','talked'], answer:2, explain:'tell+사람+내용, say+내용(사람은 say to me). speak/talk는 that절을 직접 받지 않는다.'},
    {q:'"내 키가 더 컸으면 좋을 텐데"(현실과 반대)는?', choices:['I hope I am taller.','I want tall.','I expect to be taller.','I wish I were taller.'], answer:3, explain:'현실과 반대인 소망은 wish + 가정법 과거. 실현 가능한 바람은 hope.'},
    {q:'"그에게 전화하라고 나한테 알려 줘"는?', choices:['Remind me to call him.','Remember me to call him.','Memory me to call him.','Recall me calling him.'], answer:0, explain:'remember는 스스로 기억하다, remind는 남에게 상기시키다.'},
    {q:'"표가 거의 다 팔렸다" — ___ all the tickets are sold out.', choices:['Most','Almost','Mostly','The most'], answer:1, explain:'almost는 부사라서 almost all로 쓴다. Most tickets(대부분의 표)와 구분.'},

    {q:'"공부에 매진하다" 표현은?', choices:['hit the road','hit the books','hit the sack','hit it off'], answer:1, explain:'hit the books = 공부에 매진. hit the road는 떠나다, hit the sack는 자다.'},
    {q:'"비밀을 누설하다"는?', choices:['spill the beans','break the ice','drop the ball','break a leg'], answer:0, explain:'spill the beans가 표준 이디엄. drop the ball은 실수하다.'},
    {q:'"본론으로 들어가자"는?', choices:['cut the mustard','cut to the chase','cut corners','cut it out'], answer:1, explain:'cut to the chase = 본론으로. cut corners는 대충하다.'},
    {q:'"일이 잘 풀렸다" — Things ___ out well.', choices:['worked','gave','put','ran'], answer:0, explain:'work out = (일이) 잘 풀리다 / 운동하다.'},
    {q:'"조사해 볼게요" — I\'ll ___ the issue.', choices:['look into','look up to','look down on','look after'], answer:0, explain:'look into = 조사하다. look after는 돌보다.'},
    {q:'"프린터 용지가 다 떨어졌어" — We\'ve ___ printer paper.', choices:['run into','run out of','run over','run through'], answer:1, explain:'run out of = 고갈되다.'},
    {q:'"결론을 내리다" 연어는?', choices:['make a conclusion','draw a conclusion','do a conclusion','catch a conclusion'], answer:1, explain:'draw a conclusion이 표준 연어.'},
    {q:'"요점을 놓치다"는?', choices:['miss the point','lose the point','drop the point','fail the point'], answer:0, explain:'miss the point가 고정 표현.'},
    {q:'"제가 알기로는" 패턴은?', choices:['As long as I know','As far as I know','As soon as I know','As well as I know'], answer:1, explain:'As far as I know = 제가 아는 범위에서는.'},
    {q:'"완전 동감"에 가까운 표현은?', choices:["I couldn't agree more.",'I could agree less.','I agree never.','I am agree so much.'], answer:0, explain:"I couldn't agree more = 이보다 더 동의할 수 없다 = 완전 동의."},
    {q:'비즈니스에서 "여유·처리 능력" 비유로 쓰는 말은?', choices:['bandwidth','bluetooth','firewall','keyboard'], answer:0, explain:'bandwidth를 시간·집중 여력 비유로 씀.'},
    {q:'"오늘 업무 종료 전까지"에 쓰는 약어는?', choices:['ASAP','EOD','FYI','DIY'], answer:1, explain:'EOD = End Of Day. ASAP은 가능한 한 빨리.'},
    {q:'leave와 live를 가르는 것은?', choices:['자음','모음 /iː/ vs /ɪ/','강세 개수','무성음'], answer:1, explain:'leave는 긴 /iː/, live는 짧은 /ɪ/.'},
    {q:'desert(사막)와 dessert(디저트) 차이의 핵심은?', choices:['철자 s 개수와 강세','모음 하나','복수형','과거형'], answer:0, explain:'dessert는 s가 하나 더 있고 강세가 뒤에 가까운 경우가 많음(기억: dessert wants two sugars).'},
    {q:'"가격을 올리다" 올바른 동사는?', choices:['rise the prices','raise the prices','arise the prices','rose the prices'], answer:1, explain:'raise는 타동사(목적어 필요), rise는 자동사.'},
    {q:'affect와 effect 구분이 맞는 것은?', choices:['둘 다 명사만','affect 동사 / effect 명사(일반)','effect만 동사','같은 뜻'], answer:1, explain:'일반적으로 affect=영향을 주다, effect=결과·효과.'},
    {q:'advice / advise 맞는 문장은?', choices:['She gave me a good advise.','She advised me.','She adviced me.','Advices are helpful.'], answer:1, explain:'advise 동사, advice 불가산 명사(a good piece of advice).'},
    {q:'"책을 놓다"에 가까운 것은?', choices:['Lie the book on the desk.','Lay the book on the desk.','Lain the book.','Lying the book now as command.'], answer:1, explain:'lay(타동)=놓다. lie(자동)=눕다.'},
    {q:'win과 beat 쓰임이 맞는 것은?', choices:['We beat the trophy.','We won the match and beat the champions.','We won the champions.','We beat the victory.'], answer:1, explain:'win+경기/상, beat+상대.'},
    {q:'"이 집이 우리의 보금자리가 됐다" — This house became our ___.', choices:['house again','home','building','room'], answer:1, explain:'house는 건물, home은 정이 든 공간.'},
    {q:'"의미 있는 변화를 만들다" 비즈니스 표현은?', choices:['move the needle','move the cheese','spin the wheel','push the desk'], answer:0, explain:'move the needle = 지표를 의미 있게 움직이다.'},
    {q:'"쉬운 성과부터"에 해당하는 표현은?', choices:['high-hanging fruit','low-hanging fruit','sour grapes','bad apple'], answer:1, explain:'low-hanging fruit = 쉽게 따는 과일 = 쉬운 성과.'},
    {q:'Feel free to ... 의 뉘앙스는?', choices:['금지','편하게 ~해도 된다','명령만','사과'], answer:1, explain:'공손한 허용·초대 표현.'},
    {q:'"알고 보니" 패턴은?', choices:['It turns out that ...','It turns in that ...','It turns off that ...','It turns up that ...'], answer:0, explain:'It turns out (that) ... = 결과적으로 드러난 사실.'}

  ]
};
