export type GameId = string;

export type GroupId = "suneung" | "science" | "society" | "language" | "tech" | "symbol" | "mind";

export type KernelId =
  | "custom"
  | "bond"
  | "plates"
  | "sketch"
  | "pulse"
  | "fit"
  | "runway"
  | "allocate"
  | "funnel"
  | "route"
  | "bins"
  | "wire"
  | "place"
  | "stack"
  | "order"
  | "logic"
  | "steer"
  | "listen"
  | "meter"
  | "stroop"
  | "collect"
  | "syntax"
  | "essay"
  | "loop"
  | "journey"
  | "precept"
  | "attend"
  | "join"
  | "boxes"
  | "wheel"
  | "qi"
  | "pillars"
  | "ties"
  | "repair"
  | "savor"
  | "spoil"
  | "toeic"
  | "teps"
  | "cave"
  | "nostos"
  | "exposure"
  | "suneung";

export type GameMeta = {
  id: GameId;
  title: string;
  titleEn: string;
  subject: string;
  group: GroupId;
  kernel: KernelId;
  kindLabel: string;
  blurb: string;
  how: string;
  transfer: string;
  paper?: boolean;
};

export const GROUPS: { id: GroupId; label: string; en: string }[] = [
  { id: "suneung", label: "수능", en: "CSAT" },
  { id: "science", label: "과학", en: "Science" },
  { id: "society", label: "사회", en: "Society" },
  { id: "language", label: "언어", en: "Language" },
  { id: "tech", label: "기술", en: "Tech" },
  { id: "symbol", label: "상징", en: "Symbol" },
  { id: "mind", label: "마음", en: "Mind" },
];

export const GAMES: GameMeta[] = [
  {
    id: "cannon",
    title: "포물선 캐논",
    titleEn: "Cannon",
    subject: "물리학",
    group: "science",
    kernel: "custom",
    kindLabel: "액션 · 물리",
    blurb: "당겨서 쏘고, 바람과 움직이는 표적을 읽는다.",
    how: "포신을 잡아 뒤로 당기세요. 당긴 방향의 반대로 날아갑니다.",
    transfer: "수평 사거리는 발사각 45° 근처에서 최대가 된다.",
  },
  {
    id: "chem",
    title: "결합 실험대",
    titleEn: "Bonds",
    subject: "화학",
    group: "science",
    kernel: "bond",
    kindLabel: "조립 · 규칙",
    blurb: "원자를 끌어 원자가에 맞는 결합만 붙는다.",
    how: "원자를 다른 원자 위로 드래그하세요. 잘못된 결합은 튕깁니다.",
    transfer: "결합 수는 원자가(valence)를 따른다. H는 1, O는 2, C는 4.",
  },
  {
    id: "dna",
    title: "염기쌍",
    titleEn: "Base Pair",
    subject: "생물학",
    group: "science",
    kernel: "custom",
    kindLabel: "리듬 · 퍼즐",
    blurb: "주형이 흘러온다. A–T, G–C만 기억하면 된다.",
    how: "아래에서 상보 염기를 누르세요. 키보드 A T G C도 됩니다.",
    transfer: "DNA는 A–T, G–C 상보쌍으로 정보를 복제한다.",
  },
  {
    id: "orbit",
    title: "궤도 관제",
    titleEn: "Orbit",
    subject: "천문학",
    group: "science",
    kernel: "custom",
    kindLabel: "시뮬레이션",
    blurb: "느리면 추락, 빠르면 탈출. 원궤도 속도를 손으로 조율한다.",
    how: "위성에서 드래그해 속도 벡터를 정한 뒤 손을 떼면 발사됩니다.",
    transfer: "원궤도 속력은 √(GM/r) — 반지름이 커질수록 더 느려도 버틴다.",
  },
  {
    id: "earth",
    title: "판의 경계",
    titleEn: "Plates",
    subject: "지구과학",
    group: "science",
    kernel: "plates",
    kindLabel: "조작 · 지질",
    blurb: "판을 밀고 당겨 해령·해구·습곡을 만든다.",
    how: "두 판을 가까이, 멀리, 또는 옆으로 밀어 목표 지형을 만드세요.",
    transfer: "발산은 해령, 수렴은 해구·습곡, 보존은 변환단층.",
  },
  {
    id: "math",
    title: "곡선 스케치",
    titleEn: "Sketch",
    subject: "수학",
    group: "science",
    kernel: "sketch",
    kindLabel: "그래프",
    blurb: "점들을 밀어 점선 함수에 포갠다.",
    how: "흰 점을 드래그해 곡선을 목표 점선에 맞추세요.",
    transfer: "함수의 모양은 계수·주기·진폭이 결정한다. 손으로 계수를 읽는다.",
  },
  {
    id: "neuro",
    title: "활동전위",
    titleEn: "Spike",
    subject: "신경과학",
    group: "science",
    kernel: "pulse",
    kindLabel: "타이밍",
    blurb: "역치에 닿을 때만 불을 넘긴다. 불응기를 읽어야 한다.",
    how: "뉴런을 눌러 발화시키세요. 신호가 끝까지 닿아야 합니다.",
    transfer: "활동전위는 역치를 넘으면 전유(all-or-none)이고, 직후 불응기가 있다.",
  },
  {
    id: "stats",
    title: "분포를 맞춰라",
    titleEn: "Fit",
    subject: "경영통계",
    group: "science",
    kernel: "fit",
    kindLabel: "추정",
    blurb: "평균과 분산 손잡이를 밀어 히스토그램에 포갠다.",
    how: "아래 두 손잡이 — 평균(위치), 표준편차(폭) — 를 드래그하세요.",
    transfer: "정규분포는 평균으로 중심을, 표준편차로 퍼짐을 정한다.",
    paper: true,
  },
  {
    id: "market",
    title: "시장 청산",
    titleEn: "Clear",
    subject: "경제학",
    group: "society",
    kernel: "custom",
    kindLabel: "그래프 · 조작",
    blurb: "가격선을 밀어 잉여와 부족을 없앤다.",
    how: "가격선(가로줄)을 위아래로 드래그하세요.",
    transfer: "수요량과 공급량이 만나는 가격에서 시장이 청산된다.",
    paper: true,
  },
  {
    id: "finance",
    title: "할인된 내일",
    titleEn: "Discount",
    subject: "재무",
    group: "society",
    kernel: "runway",
    kindLabel: "시계열",
    blurb: "미래의 현금을 오늘 값으로 끌어온다.",
    how: "할인율을 조정하고, 현금흐름 칸을 눌러 목표 NPV에 맞추세요.",
    transfer: "내일의 1원은 오늘보다 작다. NPV는 할인된 현금흐름의 합.",
    paper: true,
  },
  {
    id: "invest",
    title: "포트폴리오 폭풍",
    titleEn: "Storm",
    subject: "투자",
    group: "society",
    kernel: "allocate",
    kindLabel: "배분",
    blurb: "비중을 나누고, 시장 충격을 버틴다.",
    how: "막대를 밀어 자산 비중을 나누세요. 폭풍이 오면 분산된 쪽이 덜 꺾입니다.",
    transfer: "위험은 한 바구니에 모일 때 커진다. 상관 낮은 자산이 완충한다.",
    paper: true,
  },
  {
    id: "marketing",
    title: "전환 깔때기",
    titleEn: "Funnel",
    subject: "마케팅",
    group: "society",
    kernel: "funnel",
    kindLabel: "배치",
    blurb: "떨어지는 방문객을 광고·랜딩·결제로 받는다.",
    how: "아래 타일을 깔때기 단에 놓으세요. 예산이 바닥나기 전에 전환하세요.",
    transfer: "전환은 인지→고려→행동의 단을 지나며, 단마다 손실이 난다.",
  },
  {
    id: "startup",
    title: "활주로",
    titleEn: "Runway",
    subject: "스타트업",
    group: "society",
    kernel: "runway",
    kindLabel: "자원 관리",
    blurb: "현금과 소진을 읽고 달을 넘긴다.",
    how: "채용·삭감·마케팅·투자 버튼을 눌러 목표 월까지 버티세요.",
    transfer: "활주로(runway) = 현금 ÷ 월 소진. 성장과 생존은 같은 시계를 본다.",
    paper: true,
  },
  {
    id: "law",
    title: "사실의 조문",
    titleEn: "Statute",
    subject: "법학",
    group: "society",
    kernel: "bins",
    kindLabel: "요건",
    blurb: "사건을 읽고 영역과 구성요건을 가른다.",
    how: "사실 카드를 헌법·민법·형법 쟁반에 놓고, 성립 요건을 끌어 붙이세요.",
    transfer: "같은 사건도 공법·사법·형벌의 물음이 갈라진다. 법은 라벨이 아니라 요건이다.",
    paper: true,
  },
  {
    id: "leet",
    title: "논리 격자",
    titleEn: "Grid",
    subject: "LEET",
    group: "society",
    kernel: "logic",
    kindLabel: "추리",
    blurb: "단서를 읽고 칸을 채운다. 모순이 나는 칸은 죽는다.",
    how: "단서를 보고 격자를 탭해 O/X를 정하세요. 모순 없이 채우면 통과.",
    transfer: "연역은 전제가 참이면 결론이 필연이다. 격자에서 모순을 제거하는 일.",
    paper: true,
  },
  {
    id: "politics",
    title: "연립의 수",
    titleEn: "Coalition",
    subject: "정치",
    group: "society",
    kernel: "allocate",
    kindLabel: "연합",
    blurb: "의석을 모아 과반을 만든다. 이념 거리는 비용이다.",
    how: "정당을 눌러 연립에 넣거나 빼세요. 과반이되 거리가 짧을수록 고득점.",
    transfer: "연립은 의석의 합이 아니라, 이념 거리를 치르는 거래다.",
    paper: true,
  },
  {
    id: "ideology",
    title: "좌표 위의 말",
    titleEn: "Axes",
    subject: "이념",
    group: "society",
    kernel: "place",
    kindLabel: "좌표",
    blurb: "정책을 자유–평등, 권위–해방 두 축 위에 직접 놓는다.",
    how: "카드를 좌표로 드래그하세요. 자리는 한 줄이 아니라 두 축입니다.",
    transfer: "이념은 한 줄이 아니라 두 축 위의 위치다.",
    paper: true,
  },
  {
    id: "socio",
    title: "관계망",
    titleEn: "Ties",
    subject: "사회학",
    group: "society",
    kernel: "ties",
    kindLabel: "연결",
    blurb: "강한 연결은 결속, 약한 연결은 정보. 다리를 놓아 소문을 건넌다.",
    how: "집단 사이에서 얇은 다리를 그으세요. 정보는 약한 연결로 건너갑니다.",
    transfer: "강한 연결은 결속, 약한 연결은 정보. 다리는 약한 쪽에서 생긴다.",
  },
  {
    id: "philo",
    title: "동굴의 빛",
    titleEn: "Cave",
    subject: "철학",
    group: "society",
    kernel: "cave",
    kindLabel: "비춤",
    blurb: "램프로 형상만 비춘다. 그림자에 오래 머물면 실재를 놓친다.",
    how: "램프를 형상 위에 0.7초 두세요. 움직이는 그림자는 피합니다.",
    transfer: "플라톤의 동굴: 우리가 보는 것은 종종 실재의 그림자다.",
  },
  {
    id: "era",
    title: "연표 레일",
    titleEn: "Rails",
    subject: "역사",
    group: "society",
    kernel: "custom",
    kindLabel: "분류",
    blurb: "세계사 사건을 고대부터 현대까지 아홉 레일에 끌어 앉힌다.",
    how: "사건을 해당 시대 레일 위로 드래그하세요. 연도는 맞춘 뒤에 열립니다.",
    transfer: "역사는 한 덩어리가 아니라 고대·고전·중세·근세·현대의 리듬이다.",
    paper: true,
  },
  {
    id: "english",
    title: "문장 조립",
    titleEn: "Syntax",
    subject: "영어",
    group: "language",
    kernel: "syntax",
    kindLabel: "어순",
    blurb: "주어·동사·목적어 칸에 단어를 앉혀 영어 뼈를 세운다.",
    how: "단어를 주어·동사·목적어 칸으로 드래그하세요. 자리가 뜻입니다.",
    transfer: "영어의 기본 뼈는 SVO. 수식어는 자리를 얻어야만 붙는다.",
  },
  {
    id: "chinese",
    title: "사성 듣기",
    titleEn: "Tones",
    subject: "중국어",
    group: "language",
    kernel: "listen",
    kindLabel: "청음",
    blurb: "음의 높낮이 곡선을 듣고 성조를 고른다.",
    how: "재생을 들은 뒤 1·2·3·4성을 누르세요.",
    transfer: "성조는 음절의 정체다. 마(mā má mǎ mà)는 네 단어다.",
  },
  {
    id: "writing",
    title: "문단의 뼈",
    titleEn: "Bones",
    subject: "글쓰기",
    group: "language",
    kernel: "essay",
    kindLabel: "구성",
    blurb: "주장–근거–예시–반론–맺음 칸에 문장을 앉힌다.",
    how: "문장을 주장·근거·예시·반론·맺음 칸으로 끌어 넣으세요. 남는 문장은 버립니다.",
    transfer: "설득 문단은 주장 다음에 근거, 그다음 반론, 마지막에 맺음.",
    paper: true,
  },
  {
    id: "toeic",
    title: "토익 파트",
    titleEn: "Parts 1–7",
    subject: "TOEIC",
    group: "language",
    kernel: "toeic",
    kindLabel: "파트 1–7",
    blurb: "사진·응답·대화·방송·문법·연결·단일·복수 독해를 파트별로 한다.",
    how: "각 장이 실제 파트입니다. 보기 칩을 빈칸·사진·지문에 놓으세요.",
    transfer: "파트마다 함정이 다르다. 사진에 없는 말, Wh에 대한 Yes/No, 연결어의 방향.",
  },
  {
    id: "toefl",
    title: "강의 노트",
    titleEn: "Lecture",
    subject: "TOEFL",
    group: "language",
    kernel: "listen",
    kindLabel: "청취 · 요점",
    blurb: "흘러가는 강의에서 핵심만 건진다.",
    how: "강의 문장을 주장·예시·반례·결론 칸에 앉히세요.",
    transfer: "토플 청취는 세부보다 구조 — 주장, 예시, 반례 — 를 적는다.",
  },
  {
    id: "teps",
    title: "텝스 영역",
    titleEn: "Sections",
    subject: "TEPS",
    group: "language",
    kernel: "teps",
    kindLabel: "듣기·어휘·문법·독해",
    blurb: "말의 기능, 주제 문장, 뉘앙스 함정, 수일치, 본문 안/밖을 가른다.",
    how: "각 장이 텝스 영역입니다. 동의는 교집합, 추론은 본문에 있는 말만.",
    transfer: "TEPS는 속도보다 함정. 동의어는 전체가 아니고, 추론은 본문이 안 말한 비교를 심는다.",
  },
  {
    id: "chord",
    title: "화음 쌓기",
    titleEn: "Chord",
    subject: "음악",
    group: "language",
    kernel: "custom",
    kindLabel: "청음",
    blurb: "듣고, 건반으로 다시 쌓는다.",
    how: "목표 화음을 들은 뒤 같은 음을 누르세요.",
    transfer: "장3화음은 장3도+단3도, 단3화음은 단3도+장3도.",
  },
  {
    id: "ai",
    title: "어텐션 헤드",
    titleEn: "Attend",
    subject: "인공지능",
    group: "tech",
    kernel: "attend",
    kindLabel: "주의",
    blurb: "쿼리가 관련 키에만 무게를 둔다. 정규화된 주의가 보인다.",
    how: "키를 밀어 가중치를 올리세요. 무관한 토큰은 거의 0이어야 합니다.",
    transfer: "어텐션은 ‘모두 보기’가 아니라 관련 토큰에 가중치를 주는 일.",
  },
  {
    id: "frontend",
    title: "박스 모델",
    titleEn: "Boxes",
    subject: "프론트엔드",
    group: "tech",
    kernel: "boxes",
    kindLabel: "레이아웃",
    blurb: "콘텐츠·패딩·보더·마진을 키워 목표 상자에 포갠다.",
    how: "아래 손잡이로 네 겹을 조절하세요. 상자가 바깥으로 자랍니다.",
    transfer: "CSS 박스는 content → padding → border → margin 순으로 자란다.",
  },
  {
    id: "backend",
    title: "미들웨어 관",
    titleEn: "Pipe",
    subject: "백엔드",
    group: "tech",
    kernel: "route",
    kindLabel: "라우팅",
    blurb: "요청을 인증·검증·핸들러 순으로 흘린다.",
    how: "관을 탭해 열고 닫아, 패킷이 올바른 순서로 통과하게 하세요.",
    transfer: "미들웨어는 체인이다. 인증이 핸들러보다 앞에 와야 한다.",
  },
  {
    id: "db",
    title: "조인 키",
    titleEn: "Join",
    subject: "데이터베이스",
    group: "tech",
    kernel: "join",
    kindLabel: "조인",
    blurb: "표의 키 열을 잇고, 맞는 행이 결과 표로 모이는 것을 본다.",
    how: "열 이름에서 끌어 조인하세요. 키 없는 연결은 곱집합이 됩니다.",
    transfer: "조인은 같은 도메인의 키로 행을 맞추는 일. 키 없는 연결은 곱집합.",
  },
  {
    id: "security",
    title: "패킷 검문",
    titleEn: "Firewall",
    subject: "보안",
    group: "tech",
    kernel: "route",
    kindLabel: "필터",
    blurb: "정상은 통과, 공격은 떨어낸다.",
    how: "규칙을 켜고 꺼 악성 패킷만 막으세요. 정상까지 막으면 감점.",
    transfer: "보안은 허용과 차단의 균형. 기본 거절(deny by default)이 출발점.",
  },
  {
    id: "harness",
    title: "루프를 닫아라",
    titleEn: "Loop",
    subject: "하네스",
    group: "tech",
    kernel: "loop",
    kindLabel: "루프",
    blurb: "계획–실행–관찰–검증 고리에 단계를 얹는다. 검증이 없으면 샌다.",
    how: "빠진 단계를 고리의 빈자리에 놓으세요. 빨간 입자가 새면 검증이 비어 있습니다.",
    transfer: "에이전트 하네스는 계획만으로 닫히지 않는다. 검증이 루프를 닫는다.",
  },
  {
    id: "astrology",
    title: "하우스에 앉히기",
    titleEn: "Houses",
    subject: "점성",
    group: "symbol",
    kernel: "wheel",
    kindLabel: "차트",
    blurb: "출생 차트의 열두 집에 행성을 앉힌다.",
    how: "행성을 휠의 하우스로 끌어 앉히세요. 행성은 무엇, 하우스는 어디.",
    transfer: "행성은 ‘무엇’, 하우스는 ‘삶의 영역’. 같은 금성도 2하우스와 7하우스가 다르다.",
  },
  {
    id: "fengshui",
    title: "기의 방위",
    titleEn: "Qi",
    subject: "풍수",
    group: "symbol",
    kernel: "qi",
    kindLabel: "공간",
    blurb: "팔괘 방에 가구를 놓고, 문에서 기가 흐르게 한다.",
    how: "가구를 끌어 문의 축을 여세요. 입구를 막으면 기가 체합니다.",
    transfer: "풍수는 대칭이 아니라 흐름 — 입구에서 막히지 않는 기.",
  },
  {
    id: "iching",
    title: "효를 쌓다",
    titleEn: "Yao",
    subject: "주역",
    group: "symbol",
    kernel: "stack",
    kindLabel: "구축",
    blurb: "아래에서 위로 음효·양효를 쌓아 괘를 만든다.",
    how: "음(끊긴 선) 또는 양(긴 선)을 눌러 아래부터 6효를 맞추세요.",
    transfer: "괘는 아래(내괘)에서 위(외괘)로 읽는다. 변화는 아래에서 시작.",
  },
  {
    id: "saju",
    title: "네 기둥",
    titleEn: "Pillars",
    subject: "사주",
    group: "symbol",
    kernel: "pillars",
    kindLabel: "명식",
    blurb: "천간·지지를 년월일시 기둥에 앉히고 오행을 읽는다.",
    how: "간지를 네 기둥에 끌어 놓으세요. 일간은 ‘나’, 월지는 계절.",
    transfer: "사주는 년월일시 네 기둥. 일간은 ‘나’, 월지는 계절·환경.",
  },
  {
    id: "tarot",
    title: "바보의 길",
    titleEn: "Fool",
    subject: "타로",
    group: "symbol",
    kernel: "journey",
    kindLabel: "서사",
    blurb: "메이저 아르카나를 바보의 여정 길 위에 세운다.",
    how: "바보를 다음 카드 문으로 데려가세요. 0에서 세계로 걷습니다.",
    transfer: "메이저는 0 바보에서 21 세계로 가는 성장 서사다.",
  },
  {
    id: "myth",
    title: "귀향",
    titleEn: "Nostos",
    subject: "신화",
    group: "symbol",
    kernel: "nostos",
    kindLabel: "항해",
    blurb: "세이렌이 배를 끌어당긴다. 눌러 돛대에 묶고 이타케로 간다.",
    how: "화면을 눌러 돛대에 묶으세요. 묶인 동안만 노래를 지나 목표에 닿습니다.",
    transfer: "노스토스(귀향)는 힘의 서사가 아니라 유혹을 거절하는 서사.",
  },
  {
    id: "religion",
    title: "계율의 길",
    titleEn: "Precepts",
    subject: "종교",
    group: "symbol",
    kernel: "precept",
    kindLabel: "전통",
    blurb: "힌두에서 이슬람까지, 그 전통의 길 위에 가르침을 얹는다.",
    how: "탐험자를 다음 가르침 돌 위로 끌어 옮기세요. 순서가 그 전통의 뼈입니다.",
    transfer: "가르침은 목록이 아니라 순서 — 계·정·혜, 믿음·행위, 오륜.",
    paper: true,
  },
  {
    id: "psy",
    title: "잉크를 읽어라",
    titleEn: "Stroop",
    subject: "심리학",
    group: "mind",
    kernel: "stroop",
    kindLabel: "주의",
    blurb: "글자가 아니라 잉크의 색을 말한다.",
    how: "단어의 뜻이 아니라 글자 색과 같은 버튼을 누르세요.",
    transfer: "스트룹: 자동 읽기가 색 이름 대기와 충돌한다. 주의는 억제다.",
  },
  {
    id: "anger",
    title: "압력 밸브",
    titleEn: "Valve",
    subject: "분노",
    group: "mind",
    kernel: "meter",
    kindLabel: "조절",
    blurb: "끓는 압력을 터뜨리지 않고 빼낸다.",
    how: "게이지가 빨간 띠에 들어가면 밸브를 눌러 내리세요. 너무 누르면 꺼집니다.",
    transfer: "분노는 신호가 먼저다. 조절은 억압이 아니라 압력의 배출 속도.",
  },
  {
    id: "fear",
    title: "손전등",
    titleEn: "Lamp",
    subject: "공포",
    group: "mind",
    kernel: "exposure",
    kindLabel: "노출",
    blurb: "손전등을 두려움에 고정한다. 눈을 돌리면 덩어리가 방을 채운다.",
    how: "손전등을 대상 위에 두세요. 작아지면 2초를 견딥니다. 피하면 커집니다.",
    transfer: "공포는 회피로 강화된다. 안전한 접근(노출)이 소거를 만든다.",
  },
  {
    id: "joy",
    title: "불씨 모으기",
    titleEn: "Embers",
    subject: "기쁨",
    group: "mind",
    kernel: "savor",
    kindLabel: "음미",
    blurb: "따뜻한 불씨만. 과열은 흘리고 리듬을 남긴다.",
    how: "이 장의 기쁨을 붙들되 과열 전에 손을 떼세요.",
    transfer: "기쁨은 각성이다. 지속되는 기쁨은 강도가 아니라 회복의 리듬.",
  },
  {
    id: "sadness",
    title: "비를 보내기",
    titleEn: "Rain",
    subject: "슬픔",
    group: "mind",
    kernel: "meter",
    kindLabel: "허용",
    blurb: "비를 막지 않고, 고이지 않게 보낸다.",
    how: "물이 차면 수문을 열어 보내세요. 완전히 말리면 실패입니다.",
    transfer: "슬픔은 유실의 신호. 삼키지도, 홍수가 되게 두지도 않는다.",
  },
  {
    id: "love",
    title: "두 궤도",
    titleEn: "Pair",
    subject: "사랑",
    group: "mind",
    kernel: "allocate",
    kindLabel: "균형",
    blurb: "나와 너의 거리를 잠근다. 너무 붙어도, 멀어도 궤도가 깨진다.",
    how: "슬라이더로 친밀과 자율의 비중을 맞추세요. 둘 다 녹색 띠에.",
    transfer: "애착은 접근과 자율의 동시 충족. 융합도, 단절도 궤도 이탈.",
  },
  {
    id: "disgust",
    title: "상한 것",
    titleEn: "Spoil",
    subject: "혐오",
    group: "mind",
    kernel: "spoil",
    kindLabel: "경계",
    blurb: "상한 것은 거르고, 사람은 더럽히지 않는다.",
    how: "접시의 경계를 지키세요. 오염은 옆을 물들입니다.",
    transfer: "혐오는 오염 회피. 문화가 대상을 바꾸지만 논리는 경계다.",
  },
  {
    id: "surprise",
    title: "예측 오차",
    titleEn: "Error",
    subject: "놀람",
    group: "mind",
    kernel: "meter",
    kindLabel: "예측",
    blurb: "다음에 올 것을 읽고, 어긋남을 흡수한다.",
    how: "예상 칸을 고른 뒤 결과를 받으세요. 오차를 너무 키우지 마세요.",
    transfer: "놀람은 예측 오차다. 학습은 오차를 줄이는 쪽으로 모델을 고친다.",
  },
  {
    id: "shame",
    title: "찢어진 끈",
    titleEn: "Repair",
    subject: "수치·죄책",
    group: "mind",
    kernel: "repair",
    kindLabel: "수리",
    blurb: "인정·듣기·사과·고침으로 끊긴 실을 다시 짠다.",
    how: "인정·듣기·사과·고침을 찢어진 실에 순서대로 꿰매세요. 숨김은 버리세요.",
    transfer: "죄책은 행위, 수치는 자기. 수리는 숨김이 아니라 다시 잇는 일.",
  },
  {
    id: "pride",
    title: "능선",
    titleEn: "Ridge",
    subject: "자부·희망",
    group: "mind",
    kernel: "steer",
    kindLabel: "등반",
    blurb: "능선을 따른다. 허영의 절벽은 반짝이지만 끝이 없다.",
    how: "등반가를 밀어 능선을 따라 정상에 오르세요. 허영의 빛은 피하세요.",
    transfer: "자부는 성취의 기록, 오만은 비교. 희망은 능선이지 절벽이 아니다.",
  },
  {
    id: "dokseo",
    title: "국어 독서",
    titleEn: "Reading",
    subject: "수능 국어",
    group: "suneung",
    kernel: "suneung",
    kindLabel: "인문·사회·과학",
    blurb: "주장이 있는 줄을 형광펜으로 찍고 함정을 지운다.",
    how: "중심 문장을 누르세요. 그다음 함정 보기를 지우세요.",
    transfer: "독서는 주장·구분 기준·지문이 허용하는 추론을 가른다.",
    paper: true,
  },
  {
    id: "munhak",
    title: "국어 문학",
    titleEn: "Literature",
    subject: "수능 국어",
    group: "suneung",
    kernel: "suneung",
    kindLabel: "갈래·표현",
    blurb: "시문을 가운데 두고 시어를 기능 칸에 붙인다.",
    how: "보기를 누른 뒤 오른쪽 기능(화자·시어·역설)을 누르세요.",
    transfer: "문학은 갈래의 형식이 정보를 얼마나 주는가다.",
    paper: true,
  },
  {
    id: "hwajak",
    title: "화법과 작문",
    titleEn: "Speech & Writing",
    subject: "수능 국어",
    group: "suneung",
    kernel: "suneung",
    kindLabel: "선택",
    blurb: "목적 → 청자 → 매체를 삼각형 꼭짓점으로 잇는다.",
    how: "꼭짓점을 그 순서로 누르세요. 매체를 먼저 고르면 글이 빕니다.",
    transfer: "화작은 목적·청자·매체가 발화와 글을 가른다.",
    paper: true,
  },
  {
    id: "eonmae",
    title: "언어와 매체",
    titleEn: "Language & Media",
    subject: "수능 국어",
    group: "suneung",
    kernel: "suneung",
    kindLabel: "선택",
    blurb: "음운에서 담화까지 아래부터 쌓는다.",
    how: "작은 단위부터 위로. 의미·표기를 단위 칸에 넣지 마세요.",
    transfer: "언매는 언어의 단위와 매체의 물질성이 문항이다.",
    paper: true,
  },
  {
    id: "csateng",
    title: "수능 영어",
    titleEn: "CSAT English",
    subject: "수능 영어",
    group: "suneung",
    kernel: "suneung",
    kindLabel: "주제·빈칸·순서",
    blurb: "Yet/However를 찍은 뒤 주제를 고른다.",
    how: "방향이 꺾이는 단어를 먼저 누르세요. 양보는 주제가 아닙니다.",
    transfer: "수능 영어는 유형이 곧 읽는 순서다.",
    paper: true,
  },
  {
    id: "khist",
    title: "한국사",
    titleEn: "Korean History",
    subject: "수능 한국사",
    group: "suneung",
    kernel: "suneung",
    kindLabel: "전근대·근현대",
    blurb: "사건을 연표 왼→오른쪽으로 올린다.",
    how: "먼저 일어난 것부터. 순서를 뒤집는 보기는 버리세요.",
    transfer: "한국사는 인과보다 먼저 순서를 고정한다.",
    paper: true,
  },
  {
    id: "mathcsat",
    title: "수학 공통",
    titleEn: "Math",
    subject: "수능 수학",
    group: "suneung",
    kernel: "suneung",
    kindLabel: "수Ⅰ·수Ⅱ",
    blurb: "성립하는 항등식을 두드린다.",
    how: "합의 로그, 곱의 미분처럼 안 되는 식을 피하세요.",
    transfer: "공통 수학은 공식의 조건(정의역, 단위)이 점수다.",
    paper: true,
  },
  {
    id: "probstat",
    title: "확률과 통계",
    titleEn: "Probability",
    subject: "수능 수학",
    group: "suneung",
    kernel: "suneung",
    kindLabel: "선택",
    blurb: "표본 점을 눌러 사건을 남긴다.",
    how: "조건이 자르는 점만 고르세요. 밖을 누르면 깎입니다.",
    transfer: "확통은 표본공간이 줄어드는 순간을 표시하는 일이다.",
    paper: true,
  },
  {
    id: "calc",
    title: "미적분",
    titleEn: "Calculus",
    subject: "수능 수학",
    group: "suneung",
    kernel: "suneung",
    kindLabel: "선택",
    blurb: "영점을 찍고 부호를 지울지 고른다.",
    how: "축을 뚫는 점을 모두 누른 뒤, 넓이인지 정적분인지 고르세요.",
    transfer: "미적은 부호를 언제 지울지가 문항이다.",
    paper: true,
  },
  {
    id: "geom",
    title: "기하",
    titleEn: "Geometry",
    subject: "수능 수학",
    group: "suneung",
    kernel: "suneung",
    kindLabel: "선택",
    blurb: "곡선을 보고 초점·합·차 정의를 고른다.",
    how: "타원은 합 2a, 쌍곡선은 차 2a, 포물선은 초점=준선.",
    transfer: "기하는 정의(초점·준선)가 공식보다 앞선다.",
    paper: true,
  },
  {
    id: "lifeeth",
    title: "생활과 윤리",
    titleEn: "Life Ethics",
    subject: "수능 사탐",
    group: "suneung",
    kernel: "suneung",
    kindLabel: "선택",
    blurb: "사례를 사상가의 저울에 올린다.",
    how: "같은 사례라도 척도가 바뀌면 판결이 바뀝니다.",
    transfer: "생윤은 같은 사례를 다른 척도로 다시 재는 일이다.",
    paper: true,
  },
  {
    id: "thought",
    title: "윤리와 사상",
    titleEn: "Thought",
    subject: "수능 사탐",
    group: "suneung",
    kernel: "suneung",
    kindLabel: "선택",
    blurb: "인성론·이기론 이름을 저울에 올린다.",
    how: "호발, 기발리승, 일반의지처럼 이름이 곧 문항입니다.",
    transfer: "윤사는 이름(호발, 일반의지)이 곧 문항이다.",
    paper: true,
  },
  {
    id: "smun",
    title: "사회문화",
    titleEn: "Society",
    subject: "수능 사탐",
    group: "suneung",
    kernel: "suneung",
    kindLabel: "선택",
    blurb: "같은 사실을 기능/갈등 렌즈로 가른다.",
    how: "왼쪽·오른쪽 렌즈를 고르세요. 같은 숫자도 문장이 달라집니다.",
    transfer: "사문은 방법과 관점이 같은 현상을 다르게 보이게 한다.",
    paper: true,
  },
  {
    id: "polilaw",
    title: "정치와 법",
    titleEn: "Politics & Law",
    subject: "수능 사탐",
    group: "suneung",
    kernel: "suneung",
    kindLabel: "선택",
    blurb: "안건을 기관 책상에 찍는다.",
    how: "안건을 고른 뒤 국회·행정부·헌재·대법을 누르세요.",
    transfer: "정법은 기관과 규범의 위계가 점수다.",
    paper: true,
  },
  {
    id: "econ",
    title: "경제",
    titleEn: "Economics",
    subject: "수능 사탐",
    group: "suneung",
    kernel: "suneung",
    kindLabel: "선택",
    blurb: "수요·공급 곡선 전체를 손으로 민다.",
    how: "곡선을 왼쪽·오른쪽으로. 곡선 위 점(수요량)과 가리세요.",
    transfer: "경제는 기회비용과 유인, 그리고 누락된 항이다.",
    paper: true,
  },
  {
    id: "korgeo",
    title: "한국지리",
    titleEn: "Korean Geography",
    subject: "수능 사탐",
    group: "suneung",
    kernel: "suneung",
    kindLabel: "선택",
    blurb: "지도에서 서해·울릉·제주를 찍는다.",
    how: "지명 칸을 누르세요. 갯벌은 서해, 울릉은 겨울 눈.",
    transfer: "한국지리는 지형과 계절 배분이 자료를 가른다.",
    paper: true,
  },
  {
    id: "worldgeo",
    title: "세계지리",
    titleEn: "World Geography",
    subject: "수능 사탐",
    group: "suneung",
    kernel: "suneung",
    kindLabel: "선택",
    blurb: "기후대·지형을 지도 칸에 찍는다.",
    how: "열대·사막·지중해·몬순의 자리를 누르세요.",
    transfer: "세계지리는 기압대와 가치 사슬의 위치다.",
    paper: true,
  },
  {
    id: "worldhist",
    title: "세계사",
    titleEn: "World History",
    subject: "수능 사탐",
    group: "suneung",
    kernel: "suneung",
    kindLabel: "선택",
    blurb: "혁명·대전을 연표에 시간 순으로 올린다.",
    how: "왼쪽이 먼저. 조공은 식민이 아닙니다.",
    transfer: "세계사는 정체의 이름과 강화의 구멍이 문항이다.",
    paper: true,
  },
  {
    id: "eahist",
    title: "동아시아사",
    titleEn: "East Asia",
    subject: "수능 사탐",
    group: "suneung",
    kernel: "suneung",
    kindLabel: "선택",
    blurb: "율령·은·개항을 연표에 올린다.",
    how: "왼쪽이 먼저. 율은 복제가 아니라 수용입니다.",
    transfer: "동아시아사는 수용의 필터와 은의 방향이다.",
    paper: true,
  },
  {
    id: "phys1",
    title: "물리학 I",
    titleEn: "Physics I",
    subject: "수능 과탐",
    group: "suneung",
    kernel: "suneung",
    kindLabel: "선택",
    blurb: "충돌 뒤 남는 것(운동량·K)을 고른다.",
    how: "공을 본 뒤 보존되는 칸을 누르세요. 마찰은 역학적을 깨뜨립니다.",
    transfer: "물1은 보존되는 것과 안 되는 것을 가른다.",
    paper: true,
  },
  {
    id: "chem1",
    title: "화학 I",
    titleEn: "Chemistry I",
    subject: "수능 과탐",
    group: "suneung",
    kernel: "suneung",
    kindLabel: "선택",
    blurb: "반응식 계수를 +/- 로 맞춘다.",
    how: "계수 비 = 몰 비. 질량 비로 맞추지 마세요.",
    transfer: "화1은 개수(몰)로 바꿔 비교하는 일이다.",
    paper: true,
  },
  {
    id: "bio1",
    title: "생명과학 I",
    titleEn: "Biology I",
    subject: "수능 과탐",
    group: "suneung",
    kernel: "suneung",
    kindLabel: "선택",
    blurb: "혈당·전위를 위/아래 화살로 맞춘다.",
    how: "올리기인지 내리기인지 화살을 누르세요.",
    transfer: "생1은 방향(올리기/내리기)과 분열의 단계가 함정이다.",
    paper: true,
  },
  {
    id: "earth1",
    title: "지구과학 I",
    titleEn: "Earth I",
    subject: "수능 과탐",
    group: "suneung",
    kernel: "suneung",
    kindLabel: "선택",
    blurb: "두 판을 밀고 당겨 해령·해구·변환을 만든다.",
    how: "판을 벌리거나 밀거나 어긋내세요. 경계의 이름이 문항입니다.",
    transfer: "지1은 경계의 이름과 순환의 원인이 문항이다.",
    paper: true,
  },
];

export function gameById(id: string): GameMeta | undefined {
  return GAMES.find((g) => g.id === id);
}

export function gamesIn(group: GroupId): GameMeta[] {
  return GAMES.filter((g) => g.group === group);
}
